import { Fragment } from 'react';
import type { PropsWithChildren, ReactNode } from 'react';
import type { InboxItem, SkillDetail } from '../../backend/types';
import { Avatar, BoardTable, LiftFigure, RichText, Small, TerminalHint, VerdictChip } from '../../components/domain/Primitives';
import { EvaluationReport, FigureRecord, ReportCaption, ReportHeading, ReportParagraph } from '../../components/domain/EvaluationReport';
import { liftLabel } from '../../components/domain/verdict';
import { Chip } from '../../components/ui/Chip';

type ItemProps = { item: InboxItem };
function required<T>(value: T | undefined | null, item: InboxItem, field: string): T {
  if (value == null) throw new Error(`Inbox ${item.id}.${field} is missing.`);
  return value;
}
function inboxAgo(days: number) { return days === 0 ? 'today' : days === 1 ? '1 day ago' : `${days} days ago`; }
function iso(item: InboxItem, days: number) { const date = new Date(item.date + 'T12:00:00Z'); date.setUTCDate(date.getUTCDate() + item.days - days); return date.toISOString().slice(0, 10); }
function Title({ children, chip }: PropsWithChildren<{ chip?: ReactNode }>) { return <div className="report-title"><span>{children}</span>{chip}</div>; }
function RunLine({ parts }: { parts: (string | undefined)[] }) { return <div className="report-run">{parts.filter(Boolean).map((part, i) => <Fragment key={i}>{i > 0 && <span className="report-dot">·</span>}<span>{part}</span></Fragment>)}</div>; }
function Abstract({ lead, children }: PropsWithChildren<{ lead: string }>) { return <div className="report-abstract"><ReportParagraph><strong>{lead}</strong> {children}</ReportParagraph></div>; }
function Mono({ children }: PropsWithChildren) { return <span className="board-mono">{children}</span>; }
function AlertChip() { return <span className="inbox-alert-chip">ALERT</span>; }
function Grants({ grants, added = [] }: { grants: string[]; added?: string[] }) { return <div className="inbox-grants">{added.map(g => <span className="inbox-added-grant" key={g}>+ {g}</span>)}{grants.map(g => <Chip key={g}>{g}</Chip>)}{!grants.length && !added.length && <Small>None · runs with the session's own permissions</Small>}</div>; }
function Record({ item, installed = false }: ItemProps & { installed?: boolean }) {
  const r = required(item.summary, item, 'summary');
  const rows = [{ label: 'vs baseline', wlt: [r.w, r.l, r.t] as [number, number, number], holes: 0, lift: liftLabel(r), p: r.signP }];
  if (installed) {
    const values = required(item.incumbent, item, 'incumbent'), lift = required(item.incumbentLift, item, 'incumbentLift');
    const w = required(values[0], item, 'incumbent.0'), l = required(values[1], item, 'incumbent.1'), t = required(values[2], item, 'incumbent.2');
    rows.push({ label: 'vs installed', wlt: [w, l, t], holes: 0, lift: `${lift[0] > 0 ? '+' : lift[0] < 0 ? '−' : '±'}${Math.abs(lift[0])}%`, p: lift[1] });
  }
  return <FigureRecord rows={rows}/>;
}
function Provenance({ item }: ItemProps) { return <Small>{item.actor?.handle} · {inboxAgo(required(item.eval_days, item, 'eval_days'))} · sonnet · agent CLI 2.34.0 · k=3</Small>; }
function Verdict({ item }: ItemProps) { return <><div className="inbox-verdict"><LiftFigure summary={item.summary}/><div className="board-column" style={{ gap: 4 }}><div className="inbox-grants"><Chip>{item.size}</Chip><Chip>{item.installs}</Chip></div><Provenance item={item}/></div></div><Record item={item}/><ReportCaption kind="Figure" n={1}>Candidate round record on {item.actor?.handle}'s run, {item.summary?.n} rounds (win–tie–loss).</ReportCaption></>; }
const syncCommand = 'npx -y terum-skills@latest sync';
function evalCommand(item: InboxItem) { return `npx -y terum-skills@latest eval ${item.name} --k 3 --commit`; }
export function ShareReport({ item: it, acted }: ItemProps & { acted: boolean }) {
  const grants = required(it.grants, it, 'grants'), who = required(it.actor, it, 'actor').handle;
  return <><Title chip={<VerdictChip summary={it.summary}/>}>{it.name}, v <Mono>{it.version}</Mono></Title><RunLine parts={[it.size, it.installs, grants.length ? `${grants.length} tool grant${grants.length === 1 ? '' : 's'}` : 'no tool grants']}/><Abstract lead={acted ? 'Installed.' : 'Shared with you.'}>{acted ? `${who} published ${it.name} to ${it.scope}; you installed version ${it.version} on this machine and it is recorded in your people file.` : `${who} published ${it.name} to ${it.scope}. A new ${it.scope === 'Global' ? 'global' : 'project'} skill is never placed on your machine without your say: install it, or decline and it will not be offered again.`} <strong>Description:</strong> <RichText text={it.desc}/></Abstract><ReportHeading n={1}>Verdict</ReportHeading><Verdict item={it}/><ReportHeading n={2}>Tool grants {acted ? 'approved' : 'to approve'}</ReportHeading><Grants grants={grants}/><ReportParagraph>{grants.length ? acted ? 'Approved on this machine; a changed grant set will ask again.' : 'Approved once per machine; a changed grant set asks again.' : "It declares no tools, so it runs with the session's own permissions."}</ReportParagraph><ReportHeading n={3}>{acted ? 'Installed' : 'Installing'}</ReportHeading><ReportParagraph>{acted ? `Version ${it.version} sits in ~/.claude/skills/${it.name} and loads in every session. Sync keeps it at the team version; remove it any time from the skill page.` : `Install copies version ${it.version} into ~/.claude/skills/${it.name} and records it in your people file. Decline adds it to your declined list; only an explicit install brings it back.`}</ReportParagraph><TerminalHint command={`npx -y terum-skills@latest ${acted ? 'uninstall-skill' : 'install'} ${it.skillRef}`}/></>;
}
export function OfftargetReport({ item: it }: ItemProps) {
  const rc = required(it.receipt, it, 'receipt'), numbers = required(it.reportNumbers, it, 'reportNumbers'), fired = required(it.fired, it, 'fired'), precision = required(numbers.precisionObserved, it, 'reportNumbers.precisionObserved'), tg = rc.triggers;
  return <><Title chip={<AlertChip/>}>{it.name} is firing off-target</Title><RunLine parts={[`observed ${iso(it, 6)} → ${it.date}`, `${it.sessions} sessions`, 'this machine', `v ${it.version}`]}/><Abstract lead="Alert.">In {it.sessions} sessions this week {it.name} was selected on {fired.length} prompts that had nothing to do with a deploy. Its receipt measured precision {tg.precision} on {numbers.triggerTotal} distractors; observed precision is {precision}. Nothing on disk changed.</Abstract><ReportHeading n={1}>Off-target prompts</ReportHeading>{fired.map(([p, d], i) => <span className="inbox-fired board-mono" key={i}>FIRED: "{p}" · {iso(it, Number(d))}</span>)}<ReportHeading n={2}>Against the receipt</ReportHeading><ReportCaption kind="Table" n={1}>Trigger selection: the receipt ({rc.runner}'s run, {rc.date}) against this machine, this week.</ReportCaption><BoardTable mono headers={['', 'Receipt', 'Observed']} widths={[0, 96, 96]} strong={['0:2', '2:2']} rows={[[ 'precision', tg.precision, precision ], ['recall', tg.recall, '1.00'], ['false fires', `${tg.fp} of ${numbers.triggerTotal}`, `${fired.length} of ${it.sessions}`]]}/><ReportHeading n={3}>What you can do</ReportHeading><ReportParagraph>Disable it here; its files stay on disk. Or re-run the eval with these {fired.length} prompts as distractor cases, so the receipt says what this machine sees. {it.author.handle} wrote it and can tighten its trigger.</ReportParagraph><TerminalHint command={evalCommand(it)}/></>;
}
export function RegressionReport({ item: it }: ItemProps) {
  const prev = required(it.previous, it, 'previous');
  // The DTO omits the previous receipt summary. This is the raw verdict printed by report_regression for this board.
  const previous = '+11% NEUTRAL';
  return <><Title chip={<VerdictChip summary={it.summary}/>}>{it.name} regressed to FAIL</Title><RunLine parts={[`v ${it.version}`, `previous ${previous} on ${prev.version}`]}/><Abstract lead="Alert.">The latest receipt for {it.name} is a FAIL: {liftLabel(it.summary)} against no skill over {it.summary?.n} paired runs. The previous version scored {previous} on {prev.runner}'s run {inboxAgo(prev.days)}. <strong>Attribution:</strong> {it.attribution}.</Abstract><ReportHeading n={1}>The record</ReportHeading><Record item={it}/><ReportCaption kind="Figure" n={1}>Candidate round record on {it.actor?.handle}'s run of {it.version}, {it.summary?.n} rounds (win–tie–loss).</ReportCaption><Provenance item={it}/><ReportHeading n={2}>What you can do</ReportHeading><ReportParagraph>Disable it here until {it.author.handle} ships a fix; the receipt stays on the skill page for anyone deciding whether to install. Or open the evals to see which cases it loses.</ReportParagraph><TerminalHint command={evalCommand(it)}/></>;
}
export function MissingReport({ item: it }: ItemProps) { const missing = required(it.missing, it, 'missing'); return <><Title chip={<AlertChip/>}>{it.name} is missing {missing.length} files</Title><RunLine parts={['found at the last sync', `v ${it.version}`]}/><Abstract lead="Alert.">The placed copy of {it.name} reads files that are not there. Every session that selects it fails at the first reference.</Abstract><ReportHeading n={1}>Missing files</ReportHeading><ReportCaption kind="Table" n={1}>Files the skill references that are absent from the placed copy.</ReportCaption><BoardTable mono headers={['File', 'Referenced from']} widths={[0, 200]} rows={missing}/><ReportHeading n={2}>What re-placing does</ReportHeading><ReportParagraph>Re-place copies the team version {it.version} over the placed copy; your copy moves to ~/.terum/skills/quarantine/ first, nothing is deleted. If the files are missing in the team repo too, {it.author.handle} owns the fix.</ReportParagraph><TerminalHint command={syncCommand}/></>; }
export function LocalReport({ item: it }: ItemProps) { const diff = required(it.diff, it, 'diff'); return <><Title chip={<VerdictChip summary={it.summary}/>}>Your copy of {it.name} differs from <Mono>{it.version}</Mono></Title><RunLine parts={[diff.map(([f, , n]) => `${f} ${n}`).join(', '), `team version by ${it.author.handle}`]}/><Abstract lead="Alert.">Placed copies are generated output, not a place to edit. The next sync moves yours to ~/.terum/skills/quarantine/ and places {it.author.handle}'s version. Nothing is deleted.</Abstract><ReportHeading n={1}>The difference</ReportHeading><ReportCaption kind="Table" n={1}>Files in your copy that differ from {it.version}.</ReportCaption><BoardTable mono headers={['File', 'Change', 'Lines']} widths={[0, 90, 90]} rows={diff}/><ReportHeading n={2}>What you can do</ReportHeading><ReportParagraph>Restore the team version now, or keep working and let sync quarantine the copy. To keep the change, send it to {it.author.handle}, or share it as a skill of your own.</ReportParagraph><TerminalHint command={syncCommand}/></>; }
export function EvalReport({ item, detail }: ItemProps & { detail: SkillDetail }) { return <div className="inbox-evaluation"><EvaluationReport name={item.name} version={item.version} receipt={required(item.receipt, item, 'receipt')} summary={required(item.summary, item, 'summary')} incumbentLift={item.incumbentLift} numbers={required(item.reportNumbers, item, 'reportNumbers')} method={detail.method}/></div>; }
export function AuthorReport({ item: it }: ItemProps) { const digest = required(it.digest, it, 'digest'); return <><Title chip={<VerdictChip summary={it.summary}/>}>{it.name} · activity</Title><RunLine parts={['last 30 days', 'a skill you wrote', `${it.installs_n} installs`, `v ${it.version}`]}/><Abstract lead="Your skill."><span>Two teammates installed deploy-check, three ran an eval on it and one favorited it.</span> Nothing needs doing; this is what the team did with it.</Abstract><ReportHeading n={1}>What happened</ReportHeading><div className="inbox-events">{digest.events.map(([ini, text, days], i) => <div key={i}><Avatar initials={String(ini)} size={22}/><span><RichText text={String(text)} bold/></span><Small>{inboxAgo(Number(days))}</Small></div>)}</div></>; }
export function TeamReport({ item: it }: ItemProps) { const who = required(it.actor, it, 'actor'); return <><Title>{who.handle} joined {it.scope}</Title><RunLine parts={[`invited by ${it.author.handle}`, who.role]}/><Abstract lead="Team.">{who.handle} accepted the invitation and installed the {it.installed_n} global skills. {it.later?.length ? `Since then she installed ${it.later.map(([n, d]) => `${n} (${d})`).join(', ')} and approved its tool grants.` : ''}</Abstract><ReportHeading n={1}>Where to find her</ReportHeading><ReportParagraph>Members lists {who.handle} with her handle, teams and last-seen time; her people file is people/{who.handle}.json in the team repo.</ReportParagraph></>; }
export function InboxReport({ item, acted, detail }: ItemProps & { acted: boolean; detail?: SkillDetail }) {
  switch (item.sub ?? item.kind) {
    case 'share': return <ShareReport item={item} acted={acted}/>;
    case 'offtarget': return <OfftargetReport item={item}/>;
    case 'regression': return <RegressionReport item={item}/>;
    case 'missing': return <MissingReport item={item}/>;
    case 'local': return <LocalReport item={item}/>;
    case 'eval': return detail ? <EvalReport item={item} detail={detail}/> : null;
    case 'author': return <AuthorReport item={item}/>;
    case 'team': return <TeamReport item={item}/>;
    default: throw new Error(`Unknown inbox report kind: ${item.sub ?? item.kind}`);
  }
}
