import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { App } from '../../app/App';
import { Providers } from '../../app/providers';
import { useUiStore } from '../../app/store';
import { BackendContext } from '../../backend';
import { createMockBackend } from '../../backend/mock';
import { createRun } from '../../backend/mock/run';
import { design } from '../../backend/mock/data';
const backend=createMockBackend();
function open(route:string){location.hash=route;return render(<Providers><BackendContext value={backend}><App/></BackendContext></Providers>);}
beforeEach(()=>{localStorage.clear();useUiStore.getState().setTheme('dark');});
afterEach(()=>{cleanup();location.hash='';vi.restoreAllMocks();});
it('renders Members in roster order with twelve members and one invited row',async()=>{open('#/share');const table=await screen.findByRole('table',{name:'Members'});await screen.findByTestId('member-row-5');expect(within(table).getAllByRole('row')).toHaveLength(14);for(const [i,member] of design.ROSTER.entries())expect(screen.getByTestId('member-row-'+i)).toHaveTextContent(member.name);expect(screen.getByTestId('invited-row')).toHaveTextContent('Sam Ortiz');expect(screen.getByText('12 members · 1 invitation')).toBeInTheDocument();});
it('renders the full invite form and exact join command',async()=>{open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});const dialog=screen.getByRole('dialog');expect(dialog).toHaveTextContent('npx -y terum-skills@latest setup terum/team-skills');expect(within(dialog).getAllByRole('radio')).toHaveLength(2);expect(within(dialog).getByRole('textbox',{name:'GitHub logins'})).toHaveValue('sortiz');await waitFor(()=>expect(document.documentElement.dataset.appReady).toBe('true'));});
it('invites with logins, scope, and role and closes only after success',async()=>{const invite=vi.spyOn(backend,'invite');open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(invite).toHaveBeenCalledWith({logins:['sortiz'],scope:'Terum',role:'member',team:'terum'});expect(location.hash).toBe('#/share');});
it.each(['','bad/login','@someone','-invalid'])('rejects invalid invite logins %j without starting a run',async(value)=>{const invite=vi.spyOn(backend,'invite');open('#/share?dialog=invite');fireEvent.change(await screen.findByRole('textbox',{name:'GitHub logins'}),{target:{value}});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));expect(await screen.findByRole('alert')).toHaveTextContent('Enter valid GitHub logins');expect(invite).not.toHaveBeenCalled();});
it('keeps the invite open and displays a failed result',async()=>{vi.spyOn(backend,'invite').mockImplementation(()=>createRun(async()=>({ok:false,error:'Invitation denied.'})));open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));expect(await screen.findByRole('alert')).toHaveTextContent('Invitation denied.');expect(screen.getByRole('dialog')).toBeInTheDocument();});
it('opens a prompt dialog for an unexpected invite question',async()=>{vi.spyOn(backend,'invite').mockImplementation(()=>createRun(async ctx=>{const answer=await ctx.ask('confirm','Allow this invitation?');return answer?{ok:true,value:{invited:['sortiz'],already:[],failed:[]}}:{ok:false,error:'Declined.'};}));open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));await screen.findByText('Allow this invitation?');fireEvent.click(screen.getByRole('button',{name:'Yes'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());});
it('renders the team-of-one state and preserves the board sidebar counts',async()=>{open('#/share?__mock=empty');await screen.findByText('Just you so far');expect(screen.getAllByTestId(/^member-row-/)).toHaveLength(1);expect(screen.queryByTestId('invited-row')).toBeNull();expect(await screen.findByRole('link',{name:'Global 15'})).toBeInTheDocument();for(const name of ['Pushes 3','Updates 3','Alerts 8'])expect(screen.getByRole('link',{name})).toBeInTheDocument();});
it('renders the exact ENOENT people error',async()=>{open('#/share?__mock=error');expect(await screen.findByRole('alert')).toHaveTextContent("ENOENT: no such file or directory, scandir '~/.terum/skills/teams/terum/people'");expect(screen.queryByRole('table')).toBeNull();});
it('renders thirteen skeletons with settled loading readiness and hidden counts',async()=>{open('#/share?__mock=loading');expect(screen.getAllByTestId('member-skeleton')).toHaveLength(13);await waitFor(()=>expect(document.documentElement.dataset.appReady).toBe('true'));expect(document.querySelectorAll('.nav-count')).toHaveLength(0);});
it('searches members without changing roster indices',async()=>{open('#/share');await screen.findByTestId('member-row-5');const member=design.ROSTER[5];if(!member)throw new Error('Missing sixth member');fireEvent.change(screen.getByRole('textbox',{name:'Find members'}),{target:{value:member.handle}});expect(await screen.findByTestId('member-row-5')).toHaveTextContent(member.name);expect(screen.getAllByTestId(/^member-row-/)).toHaveLength(1);});
it('renders read-only permission chips from roster status, never from prefs',async()=>{const member=design.ROSTER[5];if(!member)throw new Error('Missing sixth member');backend.prefs.set('role:'+member.handle,design.MEMBER[member.handle]?.[0]==='admin'?'member':'admin');open('#/share');await screen.findByTestId('member-row-5');const row=screen.getByTestId('member-row-5');const chip=row.querySelector('.member-role');expect(chip).toHaveTextContent(design.MEMBER[member.handle]?.[0]==='admin'?'Admin':'Member');expect(chip).toHaveClass(design.MEMBER[member.handle]?.[0]==='admin'?'admin':'member');expect(chip?.tagName).toBe('SPAN');expect(screen.queryByRole('button',{name:'Role for '+member.handle})).toBeNull();expect(screen.queryByRole('menuitem')).toBeNull();});
it('removes a team member through the backend and stays on Share',async()=>{const remove=vi.spyOn(backend,'team');open('#/share');await screen.findByTestId('member-row-5');const member=design.ROSTER[5];if(!member)throw new Error('Missing sixth member');fireEvent.click(within(screen.getByTestId('member-row-5')).getByRole('button',{name:'Remove from team'}));await waitFor(()=>expect(remove).toHaveBeenCalledWith({kind:'remove',handle:member.handle}));expect(location.hash).toBe('#/share');});
it("renders '—' for an unknown permission and never defaults to Member",async()=>{const roster=await backend.roster();if(!roster.ok)throw new Error(roster.error);const member=design.ROSTER[5];if(!member)throw new Error('Missing sixth member');vi.spyOn(backend,'roster').mockResolvedValue({...roster,value:{...roster.value,members:roster.value.members.map(row=>row.handle===member.handle?{...row,status:'unknown'}:row)}});open('#/share');await screen.findByTestId('member-row-5');const row=screen.getByTestId('member-row-5');expect(row.querySelector('.member-role')).toBeNull();expect(row.querySelectorAll('[role="cell"]')[1]).toHaveTextContent('—');expect(within(screen.getByTestId('member-row-0')).getByText('Admin')).toBeVisible();});
it('cancels an invitation dialog with Escape while preserving URL state',async()=>{open('#/share?dialog=invite&theme=light');await screen.findByRole('textbox',{name:'GitHub logins'});fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(location.hash).toBe('#/share?theme=light');});
it('reports invitation auxiliary data failures without claiming readiness early',async()=>{vi.spyOn(backend,'catalog').mockResolvedValue({ok:false,error:'Projects unavailable.'});open('#/share?dialog=invite');expect(await screen.findByRole('alert')).toHaveTextContent('Projects unavailable.');await waitFor(()=>expect(document.documentElement.dataset.appReady).toBe('true'));});
it('surfaces thrown roster reads as an alert',async()=>{vi.spyOn(backend,'roster').mockRejectedValue(new Error('Roster unavailable.'));open('#/share');expect(await screen.findByRole('alert')).toHaveTextContent('Roster unavailable.');});

it('waits for invitation data before marking the route ready',async()=>{const original=backend.catalog.bind(backend);let resolve:((value:Awaited<ReturnType<typeof backend.catalog>>)=>void)|undefined;vi.spyOn(backend,'catalog').mockImplementation(()=>new Promise(done=>{resolve=done;}));open('#/share?dialog=invite');await screen.findByText('Loading invitation…');expect(document.documentElement.dataset.appReady).toBeUndefined();if(!resolve)throw new Error('Invitation data was not requested');resolve(await original());await screen.findByRole('textbox',{name:'GitHub logins'});await waitFor(()=>expect(document.documentElement.dataset.appReady).toBe('true'));});
it('does not launch duplicate invitation runs while one is pending',async()=>{let finish:(()=>void)|undefined;const pending=new Promise<void>(resolve=>{finish=resolve;});const invite=vi.spyOn(backend,'invite').mockImplementation(()=>createRun(async()=>{await pending;return {ok:true,value:{invited:['sortiz'],already:[],failed:[]}};}));open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});const button=within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'});fireEvent.click(button);fireEvent.click(button);expect(invite).toHaveBeenCalledTimes(1);expect(button).toBeDisabled();finish?.();await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());});
it('cancels an active invitation run when its screen unmounts',async()=>{const run=createRun(async ctx=>{await ctx.sleep(60_000);return {ok:true,value:{invited:['sortiz'],already:[],failed:[]}};});const cancel=vi.spyOn(run,'cancel');vi.spyOn(backend,'invite').mockReturnValue(run);const view=open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));view.unmount();await waitFor(()=>expect(cancel).toHaveBeenCalled());expect((await run.done).ok).toBe(false);});

it('keeps the main landmark accessible while the invite is open',async()=>{open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});const main=screen.getByRole('main');const dialog=screen.getByRole('dialog');expect(main).toBeInTheDocument();expect(main.closest('[aria-hidden="true"], [inert]')).toBeNull();expect(main.closest('.shell')).not.toBeNull();expect(dialog.closest('.shell')).toBe(main.closest('.shell'));expect(main).not.toContainElement(dialog);});


it('keeps Invite on ShareError and omits member facets (CP-18)',async()=>{
 open('#/share');await screen.findByRole('textbox',{name:'Find members'});
 expect(screen.queryByRole('button',{name:'Filter members'})).toBeNull();
 cleanup();open('#/share?__mock=error');await screen.findByRole('alert');
 fireEvent.click(screen.getByRole('button',{name:'Invite'}));
 expect(await screen.findByRole('dialog')).toHaveTextContent('Invite members');
});
it('renders the exact join note and variadic invite placeholder (CP-05/CP-06)',async()=>{
 open('#/share?dialog=invite');const input=await screen.findByRole('textbox',{name:'GitHub logins'});
 const dialog=screen.getByRole('dialog');
 expect(dialog).toHaveTextContent("GitHub emails the invitation. The block runs the joiner's wizard: with gh signed in it accepts the pending invitation, otherwise it asks them to accept it in the browser, and git must have access to this repository.");
 fireEvent.change(input,{target:{value:''}});
 expect(dialog).toHaveTextContent('npx -y terum-skills@latest invite <github-login>...');
});

it('uses status Global and checkout root counts on the empty scenario', async () => {
  const source = backend;
  const status = await source.status();
  if (!status.ok) throw new Error(status.error);
  vi.spyOn(source, 'status').mockResolvedValue({ ...status, value: { ...status.value, counts: { Global: '71' } } });
  open('#/share?__mock=empty');
  expect(await screen.findByRole('link', { name: 'Global 71' })).toBeInTheDocument();
  expect([...document.querySelectorAll('.nav-count')].map(node=>node.textContent)).toEqual(['71','8','3','2']);
});

it('keeps job labels separate from the permission chip and preserves removal without roles',async()=>{
 const features=await backend.features();vi.spyOn(backend,'features').mockResolvedValue({...features,roles:false,memberRole:true});
 backend.prefs.set('role:ryan','admin');open('#/share');const row=await screen.findByTestId('member-row-0');
 expect(row).toHaveTextContent(design.ROSTER[0]!.role);expect(row.querySelector('.member-role')).toBeNull();
 expect(within(row).getByRole('button',{name:'Remove from team'})).toBeVisible();expect(backend.prefs.get('role:ryan','')).toBe('admin');
 for(const project of design.MEMBER.ryan?.[1]??[])expect(within(row).getByText(project)).toBeVisible();
});

it('invite from status rejects consecutive hyphens before starting a run',async()=>{const invite=vi.spyOn(backend,'invite');open('#/share?dialog=invite');fireEvent.change(await screen.findByRole('textbox',{name:'GitHub logins'}),{target:{value:'a--b'}});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));expect(await screen.findByRole('alert')).toHaveTextContent('Enter valid GitHub logins');expect(invite).not.toHaveBeenCalled();});
it('invite from status deduplicates case-insensitively preserving the first spelling',async()=>{const invite=vi.spyOn(backend,'invite');open('#/share?dialog=invite');fireEvent.change(await screen.findByRole('textbox',{name:'GitHub logins'}),{target:{value:'Sortiz, sortiz'}});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));await waitFor(()=>expect(invite).toHaveBeenCalledWith({team:'terum',logins:['Sortiz'],scope:'Terum',role:'member'}));});
it('invite from status refuses to select silently from two teams',async()=>{const settings=await backend.settings();if(!settings.ok)throw new Error(settings.error);const t=settings.value.TEAMS[0]!;vi.spyOn(backend,'settings').mockResolvedValue({...settings,value:{...settings.value,TEAMS:[t,{...t,name:'Acme',key:'acme'}]}});const invite=vi.spyOn(backend,'invite');open('#/share?dialog=invite');await waitFor(()=>expect(screen.getByRole('dialog')).toHaveTextContent('Choose a team first'));const dialog=screen.getByRole('dialog');expect(dialog).toHaveTextContent('Terum and Acme');expect(within(dialog).queryByRole('textbox',{name:'GitHub logins'})).toBeNull();fireEvent.click(within(dialog).getByRole('button',{name:'Invite'}));await waitFor(()=>expect(invite).not.toHaveBeenCalled());});
it('invite from status reports null join commands in the form and copy action',async()=>{const settings=await backend.settings();if(!settings.ok)throw new Error(settings.error);const t=settings.value.TEAMS[0]!;vi.spyOn(backend,'settings').mockResolvedValue({...settings,value:{...settings.value,TEAMS:[{...t,joinCommand:null,joinBlock:null}]}});open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});const dialog=screen.getByRole('dialog');expect(dialog.querySelector('.cli-box')).toBeNull();expect(dialog).toHaveTextContent('terum-skills reports no join command for github.com/terum/team-skills');cleanup();open('#/share?__mock=empty');fireEvent.click(await screen.findByRole('button',{name:'Copy join block'}));expect(await screen.findByRole('alert')).toHaveTextContent('no join command');});
it('invite from status copies the supplied join command',async()=>{const copy=vi.spyOn(backend,'copyToClipboard');const settings=vi.spyOn(backend,'settings');open('#/share?__mock=empty');fireEvent.click(await screen.findByRole('button',{name:'Copy join block'}));await waitFor(()=>expect(copy).toHaveBeenCalledWith('npx -y terum-skills@latest setup terum/team-skills'));expect(settings).toHaveBeenCalled();});
it('invite from status exposes partial outcomes through the mock URL',async()=>{open('#/share?dialog=invite&__mock=partial');fireEvent.change(await screen.findByRole('textbox',{name:'GitHub logins'}),{target:{value:'sortiz, bad'}});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));await waitFor(()=>expect(within(screen.getByRole('dialog')).getByRole('status')).toHaveTextContent('Invited @sortiz.'));const dialog=screen.getByRole('dialog');expect(dialog).toHaveTextContent('@bad: Could not invite @bad');expect(within(dialog).getByRole('alert')).toBeInTheDocument();});
it('invite from status shows a success notice on the page',async()=>{open('#/share?dialog=invite');await screen.findByRole('textbox',{name:'GitHub logins'});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Invite'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(await screen.findByRole('status')).toHaveTextContent('Invited @sortiz.');});
