import { token } from './presentation';
import type { PropsWithChildren } from 'react';
import type { Library } from '../../backend/types';
import { Icon } from '../ui/Icon';
import { BoardSkeleton,Small } from './Primitives';
import './Analytics.css';
export function StatTile({label,value,grow=1,children}:{label:string;value:string;grow?:number}&PropsWithChildren){return <div className="stat-tile" style={{flexGrow:grow}}><span className="stat-label">{label}</span><span className="stat-value">{value}</span>{children}</div>;}
export function Sparkline({values}:{values:number[]}){if(values.length<2)return null;const low=Math.min(...values),range=Math.max(...values)-low||1,points=values.map((v,i)=>[4+i*352/(values.length-1),4+28*(1-(v-low)/range)]),poly=points.map(p=>`${p[0]!.toFixed(1)},${p[1]!.toFixed(1)}`).join(' '),last=points.at(-1)!;return <svg width="360" height="36" viewBox="0 0 360 36" style={{display:'block',flexShrink:0,maxWidth:'100%'}}><path d={`M4.0,36 ${points.map(p=>`L${p[0]!.toFixed(1)},${p[1]!.toFixed(1)}`).join(' ')} L${last[0]!.toFixed(1)},36 Z`} fill="color-mix(in srgb,var(--tk-brand) 12%,transparent)"/><polyline points={poly} fill="none" stroke={token('brand')} strokeWidth="2" strokeLinejoin="round" strokeLinecap="round"/><circle cx={last[0]!.toFixed(1)} cy={last[1]!.toFixed(1)} r="4" fill={token('brand')} stroke={token('bg2')} strokeWidth="2"/></svg>;}
function Delta({children}:PropsWithChildren){return <div className="analytics-delta"><Icon name="arrow-up-right" size={12} color={token('good')} stroke="2"/>{children}</div>;}
export function Analytics({overview:o,zero=false,provenance='sonnet · agent CLI 2.34.0 · k=3'}:{overview:Library['overview'];zero?:boolean;provenance?:string}){const m=o.meter;return <div className="analytics-row"><StatTile label="Skills" value={zero?'0':o.skills}>{zero?<Small>{o.zero.skills}</Small>:<Delta>{o.skills_delta}</Delta>}</StatTile><StatTile label="Evaluated" value={zero?'—':o.evaluated}>{zero?<Small>{o.zero.evaluated}</Small>:<><div className="analytics-meter">{[[m.pass_,'good'],[m.neutral,'text3'],[m.fail,'bad'],[m.total-m.pass_-m.neutral-m.fail,'bg4']].map(([n,color],i)=><span key={i} style={{flexGrow:Number(n),background:`var(--tk-${color})`}}/>)}</div><Small>{o.meter_text}</Small><Small>{provenance}</Small></>}</StatTile><StatTile label="Team installs" value={zero?'0':o.installs} grow={2}>{zero?<Small>{o.zero.installs}</Small>:<><Delta>{o.installs_delta}</Delta><Sparkline values={o.sparkline}/></>}</StatTile><StatTile label="Needs attention" value={zero?'0':o.attention}>{zero?<Small>{o.zero.attention}</Small>:<><div className="board-column">{o.attention_lines.map(line=><Small key={line}>{line}</Small>)}</div><a href="#/inbox?filter=alerts" style={{fontSize:12}}>{o.attention_link}</a></>}</StatTile></div>;}
export function AnalyticsSkeleton(){return <div className="analytics-row">{[1,1,2,1].map((grow,i)=><div key={i} className="stat-tile" style={{flexGrow:grow,gap:10}}><BoardSkeleton width={56} height={10}/><BoardSkeleton width={84} height={20}/><BoardSkeleton width="70%" height={10}/></div>)}</div>;}
export function AnalyticsDivider(){return <div className="analytics-divider"><div/></div>;}
