import { useQuery } from '@tanstack/react-query';
import { useBackend } from '../../backend';
import type { PropsWithChildren } from 'react';
import type { Library } from '../../backend/types';
import { BoardSkeleton,Small } from './Primitives';
import './Analytics.css';
export function StatTile({label,value,grow=1,children}:{label:string;value:string;grow?:number}&PropsWithChildren){return <div className="stat-tile" style={{flexGrow:grow}}><span className="stat-label">{label}</span><span className="stat-value">{value}</span>{children}</div>;}
export function Analytics({overview:o,zero=false,provenance='sonnet · agent CLI 2.34.0 · k=3'}:{overview:Library['overview'];zero?:boolean;provenance?:string}){const backend=useBackend(),surfaces=useQuery({queryKey:['surfaces'],queryFn:()=>backend.surfaces()});const m=o.meter;return <div className="analytics-row"><StatTile label="Skills" value={zero?'0':o.skills}>{zero?<Small>{o.zero.skills}</Small>:<Small>{o.skills_note}</Small>}</StatTile><StatTile label="Evaluated" value={zero?'—':o.evaluated}>{zero?<Small>{o.zero.evaluated}</Small>:m.total>0?<><div className="analytics-meter">{[[m.pass_,'good'],[m.neutral,'text3'],[m.fail,'bad'],[m.total-m.pass_-m.neutral-m.fail,'bg4']].map(([n,color],i)=><span key={i} style={{flexGrow:Number(n),background:`var(--tk-${color})`}}/>)}</div><Small>{o.meter_text}</Small><Small>{provenance}</Small></>:null}</StatTile><StatTile label="Team installs" value={zero?'0':o.installs} grow={2}>{zero?<Small>{o.zero.installs}</Small>:<Small>{o.installs_note}</Small>}</StatTile><StatTile label="Needs attention" value={zero?'0':o.attention}>{zero?<Small>{o.zero.attention}</Small>:<><div className="board-column">{o.attention_lines.map(line=><Small key={line}>{line}</Small>)}</div>{o.attention_link&&surfaces.data?.inbox===true?<a href="#/inbox?filter=alerts" style={{fontSize:12}}>{o.attention_link}</a>:null}</>}</StatTile></div>;}
export function AnalyticsSkeleton(){return <div className="analytics-row">{[1,1,2,1].map((grow,i)=><div key={i} className="stat-tile" style={{flexGrow:grow,gap:10}}><BoardSkeleton width={56} height={10}/><BoardSkeleton width={84} height={20}/><BoardSkeleton width="70%" height={10}/></div>)}</div>;}
export function AnalyticsDivider(){return <div className="analytics-divider"><div/></div>;}
