import { useEffect, useRef, useState } from 'react';
import type { CSSProperties, PropsWithChildren, ReactNode } from 'react';
import { useBackend } from '../../backend';
import type { CardProvenance, ReceiptSummary } from '../../backend/types';
import { Icon } from '../ui/Icon';
import type { IconName } from '../ui/icon-paths';
import { Button } from '../ui/Button';
import { Menu,MenuTrigger,MenuPopup,MenuItem } from '../ui/Menu';
import { verdictToken, liftLabel, provenanceLine } from './verdict';
import './Primitives.css';
import { token } from './presentation';
import { decodeText } from '../../lib/fixture-text';
export function RichText({text,bold=false}:{text:string;bold?:boolean}){return text.split(/(<b>.*?<\/b>)/gs).map((part,i)=>part.startsWith('<b>')&&part.endsWith('</b>')?bold?<b key={i}>{decodeText(part.slice(3,-4))}</b>:<span key={i} style={{fontWeight:500,color:token('text1')}}>{decodeText(part.slice(3,-4))}</span>:decodeText(part));}
export function Small({children}:PropsWithChildren){return <span className="board-small">{children}</span>;}
export function SectionLabel({children,trailing}:{children:ReactNode;trailing?:ReactNode}){return <div className="board-section"><span>{children}</span>{trailing}</div>;}
export function BoardSkeleton({width,height,radius=4}:{width:number|string;height:number;radius?:number}){return <div aria-hidden="true" style={{width,height,borderRadius:radius,background:token('bg3'),flexShrink:0}}/>;}
export function IconButton({icon,label,onClick,size=24,iconSize=16,pressed=false}:{icon:IconName;label:string;onClick?:()=>void;size?:number;iconSize?:number;pressed?:boolean}){return <button type="button" className="icon-button" aria-label={label} onClick={onClick} style={{width:size,height:size,...(pressed?{background:token('bg4'),color:token('text1')}:{})}}><Icon name={icon} size={iconSize}/></button>;}
export function CommandText({command}:{command:string}){return command.split(' ').map((part,i)=><span key={i}>{i?' ':''}<span style={{display:'inline-block',overflowWrap:'anywhere'}}>{decodeText(part)}</span></span>);}
export function TerminalHint({command,prefix}:{command:string;prefix?:string}){return <div className="terminal-hint"><span className="terminal-glyph"><Icon name="terminal" size={12} stroke="2"/></span>{prefix?<span style={{whiteSpace:'nowrap'}}>{prefix} ·</span>:null}<span className="board-mono"><CommandText command={command}/></span></div>;}
export function ErrorLine({children}:PropsWithChildren){return <div className="board-error-line">{children}</div>;}
export function CenteredState({icon,title,body,primary,primaryDisabled=false,primaryReason,secondary,onPrimary,onSecondary,children,alert=false}:{icon:IconName;title:string;body:string;primary?:string;primaryDisabled?:boolean;primaryReason?:string|undefined;secondary?:string;onPrimary?:()=>void;onSecondary?:()=>void;children?:ReactNode;alert?:boolean}){return <div className="centered-state" role={alert?'alert':undefined}><div className="state-icon"><Icon name={icon} size={18}/></div><span className="state-title">{title}</span><span className="state-body">{decodeText(body)}</span><div className="state-actions">{primary?<Button kind="primary" disabled={primaryDisabled} title={primaryReason} onClick={onPrimary}>{primary}</Button>:null}{secondary?<Button onClick={onSecondary}>{secondary}</Button>:null}</div>{primaryReason?<Small>{primaryReason}</Small>:null}{children}</div>;}
export function HoverTip({children,below=true}:{children:ReactNode;below?:boolean}){return <span role="tooltip" className={'tooltip board-hover-tip'+(below?' below':'')}>{children}</span>;}
export function CopyButton({text}:{text:string}){const backend=useBackend(),[copied,setCopied]=useState(false),[error,setError]=useState<string|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);async function copy(){try{const result=await backend.copyToClipboard(text);if(!result.ok){setError(result.error);return;}setError(null);setCopied(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),1500);}catch(e){setError(e instanceof Error?e.message:'Clipboard unavailable.');}}return <span className="copy-control"><IconButton icon="copy" iconSize={14} label="Copy command" pressed={copied} onClick={()=>void copy()}/>{copied?<HoverTip below={false}>Copied</HoverTip>:null}{error?<span role="alert" className="tooltip board-hover-tip">{error}</span>:null}</span>;}
export function CliBox({command,width}:{command:string;width?:number}){return <div className="cli-box" style={width?{width}:undefined}><span className="board-mono"><CommandText command={command}/></span><CopyButton text={command}/></div>;}
export function ShareBlock({command,width}:{command:string;width?:number}){return <div className="board-column" style={{gap:6}}><SectionLabel>Share with CLI</SectionLabel><CliBox command={command} {...(width?{width}:{})}/></div>;}
export function Avatar({initials,size=24}:{initials:string;size?:number}){return <span className="board-avatar" style={{width:size,height:size,fontSize:size<=22?8:Math.round(size*.4)}}>{initials}</span>;}
export function Facepile({initials,total,label,children,testId}:{initials:string[];total:number;label:string;children?:ReactNode;testId?:string}){return <div className="board-facepile" tabIndex={children?0:undefined} data-testid={testId}><div className="board-faces">{initials.map((ini,i)=><span key={i} style={{marginLeft:i?-3:0}}><Avatar initials={ini} size={22}/></span>)}{total>initials.length?<span className="face-more">+{total-initials.length}</span>:null}</div><span className="face-label">{label}</span>{children}</div>;}
export function VerdictChip({summary,muted=false}:{summary:ReceiptSummary|null;muted?:boolean}){const {fg,bg}=verdictToken(summary,{muted}),background=bg.startsWith('tint-')?`color-mix(in srgb,var(--tk-${bg.slice(5)}) 12%,transparent)`:`var(--tk-${bg})`;return <span className={summary?'verdict-chip':'no-verdict'} data-fg={fg} data-bg={bg} style={{color:token(fg),background:summary?background:undefined}}>{summary?summary.verdict:'Not evaluated'}{summary?.partial?<span style={{fontWeight:400,marginLeft:4}}>{summary.partial[0]}/{summary.partial[1]}</span>:null}</span>;}
/**
 * A receipt's net lift under its verdict. `provenance`, when given, is reachable from the figure on
 * hover and on focus: the lift is one run's number on one model at one k, and a card must never show
 * it naked (docs/frame-protocol.md, the card-lift override of the D29 display resolution).
 */
export function LiftFigure({summary,muted=false,size=24,width=84,hideVerdict=false,provenance=null}:{summary:ReceiptSummary|null;muted?:boolean;size?:number;width?:number;hideVerdict?:boolean;provenance?:CardProvenance|null}){const tip=summary&&provenance?provenanceLine(provenance):null;return <div className="lift-figure" style={{width}} {...(tip?{tabIndex:0}:{})}><span style={{fontSize:size,lineHeight:`${size+2}px`,color:token(verdictToken(summary,{muted}).fg)}}>{liftLabel(summary)}</span>{hideVerdict?null:<VerdictChip summary={summary} muted={muted}/>}{tip?<HoverTip>{tip}</HoverTip>:null}</div>;}
export function ViewHeader({title='Global',subtitle,meta,overview,onOverview,children}:{title?:string;subtitle?:string;meta?:ReactNode;overview?:'hide'|'show';onOverview?:()=>void;children?:ReactNode}){return <div className="board-view-header"><div><Icon name={title==='Global'?'globe':'folder'} size={16} color={token('text3')}/><span style={{fontWeight:510}}>{title}</span>{subtitle?<span style={{color:token('text3')}}>{subtitle}</span>:null}{meta?<span className="board-view-meta" style={{color:token('text4')}}>{meta}</span>:null}</div><div>{overview?<Button kind="ghost" icon={overview==='hide'?'chevron-up':'chevron-down'} onClick={onOverview}>{overview==='hide'?'Hide':'Show'} overview</Button>:null}{children}</div></div>;}
/**
 * The board's search row. `filter` and `sort` are the two buttons' visible text, so the drawn default
 * ("Filter" · "Recently updated") is what renders when a caller passes neither. Giving `sortOptions`
 * turns the Sort button into a menu whose label is the current option — the default option's label is
 * the drawn string, so the row stays pixel-identical until the user picks another order.
 * `trailing` sits after the Sort button; `children` is the anchored-popover slot (the row is
 * position:relative), so a filter popover opens under the row's right edge without position:fixed.
 * A caller that renders a popover there passes `filterOpen` as well, which makes the Filter button a real
 * trigger: it reports its state to assistive tech, it closes the popover on Escape (the popover is the
 * button's SIBLING, so a keydown from the button never reaches the popover's own handler — the Library's
 * Escape did nothing at all until this landed), and it takes focus back when the popover goes away, so the
 * next Tab continues from the row instead of restarting at the top of the page. `onFilter` must therefore
 * TOGGLE, not open: it is what both the click and Escape call. `onClear` is the ✕ inside the field; a
 * caller that wants the clear to be its own navigation (a history push, say, while typing only replaces)
 * passes it, and everything else keeps the old behaviour of clearing through `onChange('')`.
 */
export function SearchRow({query,placeholder='Search 30 skills',onChange,onClear,filter='Filter',sort='Recently updated',onFilter,onSort,sortOptions,sortValue,filterOpen,trailing,children}:{query:string;placeholder?:string;onChange:(q:string)=>void;onClear?:()=>void;filter?:string;sort?:string;onFilter?:()=>void;onSort?:(value:string)=>void;sortOptions?:readonly {value:string;label:string}[];sortValue?:string;filterOpen?:boolean;trailing?:ReactNode;children?:ReactNode}){
 const label=sortOptions?.find(option=>option.value===sortValue)?.label??sort;
 const row=useRef<HTMLDivElement>(null),wasOpen=useRef(filterOpen===true);
 // When the popover closes (Escape, a commit, a second click) focus is sitting on a node that has just left
 // the document, or on <body>, and the next Tab would restart at the top of the page. The trigger takes it
 // back — and only then: focus the user has since moved somewhere real is left where they put it. The button
 // is found by class rather than by ref because `Button` does not forward one; the class carries no styling.
 useEffect(()=>{const open=filterOpen===true,closed=wasOpen.current&&!open;wasOpen.current=open;if(!closed)return;const focused=document.activeElement;if(focused!==null&&focused!==document.body&&document.contains(focused))return;row.current?.querySelector<HTMLButtonElement>('.search-filter-trigger')?.focus();},[filterOpen]);
 return <div className="board-search-row" ref={row}><div className="board-search-field"><Icon name="search" size={16}/><input aria-label={placeholder} value={query} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>{query?<IconButton icon="x" size={20} iconSize={14} label="Clear search" onClick={onClear??(()=>onChange(''))}/>:null}</div><Button kind="ghost" icon="filter" className="search-filter-trigger" aria-pressed={filterOpen} onClick={onFilter} onKeyDown={e=>{if(e.key==='Escape'&&filterOpen===true){e.stopPropagation();onFilter?.();}}}>{filter}</Button>{sortOptions?<Menu><MenuTrigger render={<Button kind="ghost" icon="sort"/>}>{label}</MenuTrigger><MenuPopup>{sortOptions.map(option=><MenuItem key={option.value} role="menuitemradio" aria-checked={option.value===sortValue} onClick={()=>onSort?.(option.value)}><span aria-hidden="true" style={{display:'inline-flex',alignItems:'center',justifyContent:'center',width:12,flexShrink:0}}>{option.value===sortValue?<Icon name="check" size={12} stroke="2.5"/>:null}</span>{option.label}</MenuItem>)}</MenuPopup></Menu>:<Button kind="ghost" icon="sort" onClick={onSort===undefined?undefined:()=>onSort(sortValue??'')}>{label}</Button>}{trailing}{children}</div>;}
export function BoardTable({headers,rows,widths,mono=false,strong=[],muted=[]}:{headers:string[];rows:ReactNode[][];widths:number[];mono?:boolean;strong?:string[];muted?:string[]}){const cellStyle=(row:number,col:number,head:boolean):CSSProperties=>({...(widths[col]?{width:widths[col],flexShrink:0}:{flexGrow:1,minWidth:0}),textAlign:col?'right':'left',fontSize:head?11:12,fontWeight:head?510:strong.includes(`${row}:${col}`)?590:col===0?500:400,color:token(head||muted.includes(`${row}:${col}`)?'text3':col===0||strong.includes(`${row}:${col}`)?'text1':'text2')});return <div role="table" className={'board-table'+(mono?' board-mono':'')}><div role="row" className="board-table-head">{headers.map((h,i)=><span role="columnheader" key={i} style={cellStyle(-1,i,true)}>{h}</span>)}</div>{rows.map((row,i)=><div role="row" key={i} className="board-table-row">{row.map((value,col)=><span role="cell" key={col} style={cellStyle(i,col,false)}>{typeof value==='string'?decodeText(value):value}</span>)}</div>)}</div>;}
