import { Providers } from '../../app/providers';
import { afterEach,expect,it } from 'vitest';
import { cleanup,render,screen } from '@testing-library/react';
import { catalogData,skillByRef,design } from '../../backend/mock/data';
import { lift_number } from '../../backend/mock/derive';
import { LiftFigure,VerdictChip } from './Primitives';
import { EvaluationReport } from './EvaluationReport';
import type { EvaluationReportProps } from './EvaluationReport';
afterEach(cleanup);
it('ranks the entire catalog by installs with stable ties',()=>{const c=catalogData();expect(c.topRated).toEqual([...c.skills].sort((a,b)=>b.installsN-a.installsN).map(s=>s.name));expect(c.topRated).not.toEqual([...c.skills].sort((a,b)=>(b.summary?.lift??-101)-(a.summary?.lift??-101)).map(s=>s.name));});
it('prints integer card lift and the absent-receipt dash',()=>{const s=catalogData().skills[0]!;render(<><LiftFigure summary={s.summary}/><LiftFigure summary={null}/></>);expect(screen.getByText(lift_number(s.summary!.lift))).toBeInTheDocument();expect(screen.getByText('—')).toBeInTheDocument();expect(screen.getByText('Not evaluated')).toBeInTheDocument();});
it('renders partial and muted verdicts as text3 on bg3',()=>{const r=skillByRef('migration-guard');if(!r.ok)throw new Error(r.error);const {container}=render(<><VerdictChip summary={r.value.summary}/><VerdictChip summary={{...r.value.summary!,partial:null}} muted/></>);expect(container.querySelectorAll('[data-fg="text3"][data-bg="bg3"]')).toHaveLength(2);});
it('reports exactly one model and CLI provenance from its receipt props',()=>{const r=skillByRef('deploy-check');if(!r.ok)throw new Error(r.error);const s=r.value;const props:EvaluationReportProps={name:s.name,version:s.version,receipt:s.receipt!,summary:s.summary!,incumbentLift:s.incumbentLift,numbers:s.reportNumbers,method:s.method};expect(props.receipt).toEqual(design.DETAIL.receipt);expect(Object.keys(props).filter(k=>k.toLowerCase().includes('receipt'))).toEqual(['receipt']);const {container}=render(<Providers><EvaluationReport {...props}/></Providers>);expect(container.querySelectorAll('[data-model]')).toHaveLength(1);expect(container.querySelector('[data-model]')).toHaveAttribute('data-model',props.receipt.model);expect(container.querySelector('[data-cc]')).toHaveAttribute('data-cc',props.receipt.cc);});
