import { token } from './presentation';
import type { PropsWithChildren } from 'react';
import type { Receipt,SkillDetail } from '../../backend/types';
import { LiftFigure,Small } from './Primitives';
import './ScoreRow.css';
export function GroupHead({label,caption}:{label:string;caption:string}){return <div className="score-group-head"><span>{label}</span><span>{caption}</span></div>;}
export function BarRow({label,fraction,value,primary=true}:{label:string;fraction:number|null;value:string;primary?:boolean}){return <div className="score-bar-row"><span>{label}</span><div>{fraction!==null?<div style={{width:`${Math.round(fraction*100)}%`,background:token(primary?'brand':'text3')}}/>:null}</div><span style={{color:token(primary?'text1':'text2')}}>{value}</span></div>;}
export function BarGroup({label,caption,rows,note,width=240}:{label:string;caption:string;rows:[string,number|null,string,boolean][];note?:string;width?:number}){return <div className="score-bar-group" style={{width}}><GroupHead label={label} caption={caption}/>{rows.map(([name,fraction,value,primary])=><BarRow key={name} label={name} fraction={fraction} value={value} primary={primary}/>)}{note?<Small>{note}</Small>:null}</div>;}
type CaseRows=NonNullable<Receipt['case_rows']>;
type CaseRunTally=NonNullable<Receipt['case_runs']>[string];
/** One pip per (case × rep) for one arm, grouped by case in the receipt's order. Filled = that rep passed every check; dashed = no verdict (the arm run failed, or the case has no checks). */
function pipsByCase(rows:CaseRows,arm:string):[string,(boolean|null)[]][]{const groups=new Map<string,(boolean|null)[]>();for(const row of rows){const reps=groups.get(row.case)??[];reps.push(row.arms[arm]?.passed??null);groups.set(row.case,reps);}return [...groups];}
export function CaseRunPips({rows,arm,primary}:{rows:CaseRows;arm:string;primary:boolean}){return <span className="case-run-pips" data-primary={primary||undefined}>{pipsByCase(rows,arm).map(([name,reps])=><span key={name} title={name}>{reps.map((passed,i)=><i key={i} data-pass={passed===true||undefined} data-unscored={passed===null||undefined}/>)}</span>)}</span>;}
/** Pips fit the 290px group up to this many case-runs per arm; past it the count stands alone and Table 1 carries the pips. */
export const MAX_STRIP_PIPS=12;
export function CaseRunRow({label,tally,rows,arm,k,primary}:{label:string;tally:CaseRunTally|null;rows:CaseRows|null;arm:string;k:number;primary:boolean}){return <div className="case-run-row"><span>{label}</span><span className="case-run-count" style={{color:token(tally&&primary?'text1':'text2')}}>{tally?<><b>{tally.passed}</b> / {tally.total} <span>{k===1?'passed cases':'case-runs'}</span></>:'—'}</span>{rows&&tally&&rows.length<=MAX_STRIP_PIPS?<CaseRunPips rows={rows} arm={arm} primary={primary}/>:null}</div>;}
/** Rev 20 (eval-engine §5.3 / §12 card slot): the receipt's `case_runs` tally stated verbatim — "1 / 3 passed cases" at k=1, "2 / 9 case-runs" otherwise — with the pips read off `case_rows`. A receipt without the fields shows "—", like no receipt at all. */
export function CaseRunGroup({receipt:rc,note,width=290}:{receipt:Receipt|null;note?:string;width?:number}){const rows=rc?.case_rows??null,tally=rc?.case_runs??null,k=rc?.k??1,cases=rows?new Set(rows.map(row=>row.case)).size:0;const caption=!tally||k===1?'cases passed, every check green':`case-runs passed · ${cases} cases × ${k} reps`;return <div className="score-bar-group" style={{width}}><GroupHead label="Quality" caption={caption}/><CaseRunRow label="with skill" tally={tally?.['candidate']??null} rows={rows} arm="candidate" k={k} primary/><CaseRunRow label="without" tally={tally?.['baseline']??null} rows={rows} arm="baseline" k={k} primary={false}/>{note?<Small>{note}</Small>:null}</div>;}
export function ScoreRow({skill:s}:{skill:SkillDetail}){const rc=s.receipt,partial=s.summary?.partial,note=partial?`over ${partial[0]} of ${partial[1]} rounds`:undefined;const roi=s.scoreFractions.roi,tg=rc?.triggers;const line=(children:PropsWithChildren['children'])=><div style={{display:'flex',alignItems:'center',height:18}}>{children}</div>;return <div className="score-row"><LiftFigure summary={s.summary} muted={!s.enabled} size={32} width={104}/><BarGroup label="ROI" caption="cost · time per run, lower wins" rows={rc&&roi?[['with skill',roi[0],`${rc.eff.candidate[2]} · ${rc.eff.candidate[1]}`,true],['without',roi[1],`${rc.eff.baseline[2]} · ${rc.eff.baseline[1]}`,false]]:[['with skill',null,'—',true],['without',null,'—',false]]} {...(note?{note}:{})}/><CaseRunGroup receipt={rc} {...(note?{note}:{})}/><div className="score-bar-group" style={{width:170}}><GroupHead label="Triggers" caption="catalog routing"/>{tg?<>{line(<span style={{fontSize:13,fontVariantNumeric:'tabular-nums'}}>routes {tg.tp} of {s.scoreFractions.routesExpected} · {tg.fp} false fire{tg.fp===1?'':'s'}</span>)}{line(<Small>recall {tg.recall} · precision {tg.precision}</Small>)}</>:line(<Small>—</Small>)}</div></div>;}
