import { token } from './presentation';
import type { PropsWithChildren } from 'react';
import type { SkillDetail } from '../../backend/types';
import { LiftFigure,Small } from './Primitives';
import './ScoreRow.css';
export function GroupHead({label,caption}:{label:string;caption:string}){return <div className="score-group-head"><span>{label}</span><span>{caption}</span></div>;}
export function BarRow({label,fraction,value,primary=true}:{label:string;fraction:number|null;value:string;primary?:boolean}){return <div className="score-bar-row"><span>{label}</span><div>{fraction!==null?<div style={{width:`${Math.round(fraction*100)}%`,background:token(primary?'brand':'text3')}}/>:null}</div><span style={{color:token(primary?'text1':'text2')}}>{value}</span></div>;}
export function BarGroup({label,caption,rows,note,width=240}:{label:string;caption:string;rows:[string,number|null,string,boolean][];note?:string;width?:number}){return <div className="score-bar-group" style={{width}}><GroupHead label={label} caption={caption}/>{rows.map(([name,fraction,value,primary])=><BarRow key={name} label={name} fraction={fraction} value={value} primary={primary}/>)}{note?<Small>{note}</Small>:null}</div>;}
export function ScoreRow({skill:s}:{skill:SkillDetail}){const rc=s.receipt,partial=s.summary?.partial,note=partial?`over ${partial[0]} of ${partial[1]} rounds`:undefined;const roi=s.scoreFractions.roi,quality=s.scoreFractions.quality,tg=rc?.triggers;const line=(children:PropsWithChildren['children'])=><div style={{display:'flex',alignItems:'center',height:18}}>{children}</div>;return <div className="score-row"><LiftFigure summary={s.summary} muted={!s.enabled} size={32} width={104}/><BarGroup label="ROI" caption="cost · time per run, lower wins" rows={rc&&roi?[['with skill',roi[0],`${rc.eff.candidate[2]} · ${rc.eff.candidate[1]}`,true],['without',roi[1],`${rc.eff.baseline[2]} · ${rc.eff.baseline[1]}`,false]]:[['with skill',null,'—',true],['without',null,'—',false]]} {...(note?{note}:{})}/><BarGroup label="Quality" caption="share of checks passed" rows={rc&&quality?[['with skill',quality[0],rc.arm.candidate.toFixed(2),true],['without',quality[1],rc.arm.baseline.toFixed(2),false]]:[['with skill',null,'—',true],['without',null,'—',false]]} {...(note?{note}:{})}/><div className="score-bar-group" style={{width:170}}><GroupHead label="Triggers" caption="catalog routing"/>{tg?<>{line(<span style={{fontSize:13,fontVariantNumeric:'tabular-nums'}}>routes {tg.tp} of {s.scoreFractions.routesExpected} · {tg.fp} false fire{tg.fp===1?'':'s'}</span>)}{line(<Small>recall {tg.recall} · precision {tg.precision}</Small>)}</>:line(<Small>—</Small>)}</div></div>;}
