import { usePreference } from '../../backend';
import type { ReactNode } from 'react';
import type { StatusResult, Surfaces, TeamStatus } from '../../backend/types';
import type { IconName } from '../ui/icon-paths';
import { Icon } from '../ui/Icon';
import { Footer } from './Footer';
function SectionHeader({label,trailing}:{label:string;trailing?:ReactNode}){return <div className="section-header"><div><span>{label}</span><Icon name="chevron-down" size={12} color="var(--tk-text4)" stroke="2"/></div>{trailing}</div>;}
function NavRow({label,icon,href,selected=false,nested=false,expandable=false,collapsed=false,onToggle,count}:{label:string;icon:IconName;href:string;selected?:boolean;nested?:boolean;expandable?:boolean;collapsed?:boolean;onToggle?:()=>void;count?:string|undefined}){
 return <a href={href} className="shell-link nav-row" aria-current={selected?'page':undefined} style={{paddingLeft:nested?32:8,background:selected?'var(--tk-bg3)':'transparent',color:selected?'var(--tk-text1)':'var(--tk-text2)'}}><div className="nav-label"><Icon name={icon} color={selected?'var(--tk-text1)':'var(--tk-text3)'}/><span>{label}</span>{expandable?<button type="button" className="icon-button" aria-label={(collapsed?'Expand ':'Collapse ')+label} aria-expanded={!collapsed} style={{width:12,height:12,flexShrink:0}} onClick={event=>{event.preventDefault();event.stopPropagation();onToggle?.();}}><Icon name={collapsed?'chevron-right':'chevron-down'} size={12} color="var(--tk-text4)" stroke="2"/></button>:null}</div>{count!==undefined?<span className="nav-count" style={{color:selected?'var(--tk-text2)':'var(--tk-text3)'}}>{count}</span>:null}</a>;
}
export function Sidebar({selected,counts,machine,me,surfaces,team,projects,collapsedSections=[],onToggleSection,onHide}:{collapsedSections?:readonly string[];onToggleSection?:(section:string)=>void;onHide?:()=>void;team?:TeamStatus|undefined;selected:string;counts:Record<string,string>|null;machine:StatusResult['machine']|undefined;me?:StatusResult['me']|undefined;surfaces?:Surfaces|undefined;projects?:readonly string[]|undefined}){
 const showCounts=usePreference('appearance:counts',true);const displayedCounts=showCounts?counts:null;
 return <aside className="sidebar"><nav className="sidebar-inner" aria-label="Main navigation"><div className="nav-group"><SectionHeader label="Library" trailing={<button type="button" className="icon-button" aria-label="Hide sidebar" aria-expanded={true} onClick={onHide} style={{width:20,height:20,color:'var(--tk-text4)'}}><Icon name="panel-left" size={14}/></button>}/>
 <NavRow label="Global" icon="globe" href="#/library/global" selected={selected==='Global'} count={displayedCounts?.Global}/>{surfaces?.library!==false&&projects&&projects.length?<><NavRow label="Projects" icon="folder" href="#/marketplace/projects" expandable collapsed={collapsedSections.includes('projects')} onToggle={()=>onToggleSection?.('projects')}/>
 {!collapsedSections.includes('projects')&&projects.map(name=><NavRow key={name} label={name} icon="box" href={'#/library/project/'+encodeURIComponent(name)} selected={selected.toLowerCase()===name.toLowerCase()} nested count={displayedCounts?.[name]}/>)}</>:null}
 {surfaces?.inbox===true?<><NavRow label="Inbox" icon="inbox" href="#/inbox" expandable collapsed={collapsedSections.includes('inbox')} onToggle={()=>onToggleSection?.('inbox')} selected={selected==='Inbox'}/>{!collapsedSections.includes('inbox')&&<><NavRow label="Pushes" icon="arrow-down-to-line" href="#/inbox?tab=pushes" nested count={displayedCounts?.Pushes}/><NavRow label="Updates" icon="refresh" href="#/inbox?tab=updates" nested count={displayedCounts?.Updates}/><NavRow label="Alerts" icon="alert" href="#/inbox?tab=alerts" nested count={displayedCounts?.Alerts}/></>}</>:null}
 </div>{surfaces?.catalog!==false||surfaces?.roster!==false?<div className="nav-group"><SectionHeader label="Team"/>{surfaces?.catalog!==false?<NavRow label="Marketplace" icon="store" href="#/marketplace" selected={selected==='Marketplace'}/>:null}{surfaces?.roster!==false?<NavRow label="Share" icon="users" href="#/share" selected={selected==='Share'}/>:null}</div>:null}</nav><Footer team={team} machine={machine} me={me} settings={selected==='Settings'}/></aside>;
}
