import { token } from './presentation';
import { decodeText } from '../../lib/fixture-text';
import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router';
import type { SkillCard as Card } from '../../backend/types';
import { useBackend, useFeatures, useCapabilities } from '../../backend';
import { Icon } from '../ui/Icon';
import type { IconName } from '../ui/icon-paths';
import { ICON_PATHS } from '../ui/icon-paths';
import { Switch } from '../ui/Switch';
import { Chip } from '../ui/Chip';
import { Menu,MenuTrigger,MenuPopup,MenuItem } from '../ui/Menu';
import { BoardSkeleton,HoverTip,LiftFigure } from './Primitives';
import './SkillCard.css';
export function SkillCard({skill}:{skill:Card}){const backend=useBackend(),location=useLocation(),origin=location.pathname.startsWith('/marketplace')?'root=marketplace':'',navigate=useNavigate(),features=useFeatures(),capabilities=useCapabilities();const [enabled,setEnabled]=useState(()=>backend.prefs.get('enabled:'+skill.name,skill.enabled)),[error,setError]=useState<string|null>(null);function pref(key:string,value:boolean,apply:(value:boolean)=>void){try{backend.prefs.set(key+':'+skill.name,value);apply(value);setError(null);}catch(e){setError(e instanceof Error?e.message:'Could not save preference.');}}return <article className="skill-card" data-testid={'skill-card-'+skill.name}><div className="skill-card-top"><LiftFigure summary={features?.liftOnCards?skill.summary:null} muted={!enabled} hideVerdict={!features?.liftOnCards}/><div className="skill-card-ident"><span>{skill.project} / {skill.category}</span><a href={'#/skill/'+encodeURIComponent(skill.name)+(origin?'?'+origin:'')} style={{color:token(enabled?'text1':'text3')}}>{skill.name}</a></div><div className="skill-card-buttons"><Menu><MenuTrigger className="icon-button card-more" aria-label={'More actions for '+skill.name}><Icon name="more" size={16}/></MenuTrigger><MenuPopup><MenuItem onClick={()=>navigate('/skill/'+skill.name+(origin?'?'+origin:''))}>Open</MenuItem>{features?.runEvalInApp?<MenuItem onClick={()=>navigate('/skill/'+skill.name+'?tab=evals&dialog=run-eval'+(origin?'&'+origin:''))}>Run eval</MenuItem>:null}{skill.placed?<MenuItem onClick={()=>navigate('/skill/'+skill.name+'?dialog=remove'+(origin?'&'+origin:''))}>Remove</MenuItem>:null}</MenuPopup></Menu>{features?.favorites&&skill.favorites!==null?<FavoriteHeart skill={skill}/>:null}</div></div><span className="skill-card-desc">{decodeText(skill.desc)}</span><div className="skill-card-bottom"><div><Chip>{skill.size}</Chip><Chip>{skill.installs}</Chip>{skill.onDiskOnly?skill.projectRoots?.map(root=><Chip key={root}>in {root}</Chip>):null}</div><div>{skill.flags.map(key=>{const indicator=skill.indicators[key];const icon=Object.hasOwn(ICON_PATHS,indicator.icon)?indicator.icon as IconName:'alert';return <span key={key} tabIndex={0} className="card-flag" data-flag={key} style={{color:token(indicator.token)}}><Icon name={icon} size={15} stroke="1.75"/><HoverTip>{decodeText(skill.flagText[key]??indicator.text)}</HoverTip></span>;})}{skill.onDiskOnly?<Chip><Icon name="check" size={12} color={token('good')}/>Installed · on this machine</Chip>:skill.placed?capabilities?.disablePerMachine?<Switch aria-label={'Enable '+skill.name} checked={enabled} onCheckedChange={value=>pref('enabled',value,setEnabled)}/>:null:<button className="card-install" onClick={()=>navigate('/skill/'+skill.name+'?__mock=not-installed&dialog=install'+(origin?'&'+origin:''))}>Install</button>}</div></div>{error?<span role="alert" className="tooltip board-hover-tip">{error}</span>:null}</article>;}
export function SkillCardSkeleton(){return <div className="skill-card card-skeleton"><div className="skill-card-top"><div className="board-column" style={{gap:4,width:84,flexShrink:0}}><BoardSkeleton width={56} height={26}/><BoardSkeleton width={44} height={20}/></div><div className="board-column" style={{gap:6,flexGrow:1}}><BoardSkeleton width="40%" height={10}/><BoardSkeleton width="60%" height={14}/></div></div><div className="board-column" style={{gap:6}}><BoardSkeleton width="100%" height={10}/><BoardSkeleton width="80%" height={10}/></div><div style={{display:'flex',gap:6}}><BoardSkeleton width={64} height={20}/><BoardSkeleton width={64} height={20}/></div></div>;}

function FavoriteHeart({skill}:{skill:Card}){const backend=useBackend(),[favorite,setFavorite]=useState(()=>backend.prefs.get('favorite:'+skill.name,skill.favorite)),[error,setError]=useState<string|null>(null);return <><button className="icon-button" aria-label={'Favorite '+skill.name} aria-pressed={favorite} onClick={()=>{try{backend.prefs.set('favorite:'+skill.name,!favorite);setFavorite(!favorite);}catch(reason){setError(String(reason));}}}><Icon name="heart" size={16} color={token(favorite?'bad':'text4')} filled={favorite}/></button>{error?<span role="alert">{error}</span>:null}</>;}
