import redditLogo from './logos/reddit.svg';
import instagramLogo from './logos/instagram.svg';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { BackendContext } from '../../../backend';
import { createMockBackend } from '../../../backend/mock';
import { ShareSkillButton } from './ShareSkillButton';
import { renderShareCard } from './render';
vi.mock('./render',()=>({renderShareCard:vi.fn()}));
const png=new Blob(['test'],{type:'image/png'});
const create=vi.fn(()=> 'blob:preview'),revoke=vi.fn();
beforeEach(()=>{Object.defineProperty(URL,'createObjectURL',{configurable:true,value:create});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:revoke});vi.mocked(renderShareCard).mockResolvedValue(png);});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.clearAllMocks();localStorage.clear();});
async function show(){const backend=createMockBackend();const result=await backend.skill({ref:'deploy-check'});if(!result.ok)throw new Error(result.error);render(<BackendContext value={backend}><ShareSkillButton skill={result.value}/></BackendContext>);fireEvent.click(screen.getByRole('button',{name:'Share deploy-check'}));return backend;}
it('generates a preview and offers preset destinations and PNG actions',async()=>{await show();expect(await screen.findByAltText('Benchmark image for deploy-check')).toBeInTheDocument();for(const name of ['Reddit','X','Instagram','LinkedIn','Copy image','Save PNG'])expect(screen.getByRole('button',{name})).toBeEnabled();expect(renderShareCard).toHaveBeenCalledWith(expect.objectContaining({name:'deploy-check',candidate:{passed:14,total:18}}),{format:'light'});});
it('copies before opening a destination and explains pasting',async()=>{const backend=await show();const copy=vi.spyOn(backend,'copyImage').mockResolvedValue({ok:true,value:undefined}),open=vi.spyOn(backend,'openUrl').mockResolvedValue({ok:true,value:undefined});await screen.findByAltText('Benchmark image for deploy-check');fireEvent.click(screen.getByRole('button',{name:'LinkedIn'}));await waitFor(()=>expect(open).toHaveBeenCalledWith('https://www.linkedin.com/feed/'));expect(copy).toHaveBeenCalledWith(png);expect(await screen.findByRole('status')).toHaveTextContent('Paste it');});
it('does not open a destination when copying fails',async()=>{const backend=await show();vi.spyOn(backend,'copyImage').mockResolvedValue({ok:false,error:'Clipboard denied'});const open=vi.spyOn(backend,'openUrl');await screen.findByAltText('Benchmark image for deploy-check');fireEvent.click(screen.getByRole('button',{name:'X'}));expect(await screen.findByText('Clipboard denied')).toBeInTheDocument();expect(open).not.toHaveBeenCalled();});
it('retries a failed generation and releases the preview on close',async()=>{vi.mocked(renderShareCard).mockRejectedValueOnce(new Error('Font failed'));await show();expect(await screen.findByText('Font failed')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Try again'}));await screen.findByAltText('Benchmark image for deploy-check');fireEvent.click(screen.getByRole('button',{name:'Close share'}));await waitFor(()=>expect(revoke).toHaveBeenCalledWith('blob:preview'));});
it('saves a skill-specific filename and leaves cancellation quiet',async()=>{const backend=await show();const save=vi.spyOn(backend,'saveImage').mockResolvedValue({ok:false,cancelled:true,error:'cancel'});await screen.findByAltText('Benchmark image for deploy-check');fireEvent.click(screen.getByRole('button',{name:'Save PNG'}));await waitFor(()=>expect(save).toHaveBeenCalledWith(png,'deploy-check-benchmark.png'));expect(screen.queryByText('cancel')).toBeNull();});

it('regenerates the selected format and saves it with a distinct filename',async()=>{const backend=await show();const save=vi.spyOn(backend,'saveImage').mockResolvedValue({ok:true,value:undefined});await screen.findByAltText('Benchmark image for deploy-check');fireEvent.click(screen.getByRole('button',{name:'Dark'}));await waitFor(()=>expect(renderShareCard).toHaveBeenLastCalledWith(expect.anything(),{format:'dark'}));await screen.findByAltText('Benchmark image for deploy-check');fireEvent.click(screen.getByRole('button',{name:'Save PNG'}));await waitFor(()=>expect(save).toHaveBeenCalledWith(png,'deploy-check-benchmark-dark.png'));});

it.each([['Reddit','https://www.reddit.com/submit'],['Instagram','https://www.instagram.com/']])('saves the PNG before opening %s, with its logo',async(name,url)=>{const backend=await show();const save=vi.spyOn(backend,'saveImage').mockResolvedValue({ok:true,value:undefined}),open=vi.spyOn(backend,'openUrl').mockResolvedValue({ok:true,value:undefined});await screen.findByAltText('Benchmark image for deploy-check');const button=screen.getByRole('button',{name});expect(button.querySelector('img')).toHaveAttribute('src',name==='Reddit'?redditLogo:instagramLogo);fireEvent.click(button);await waitFor(()=>expect(open).toHaveBeenCalledWith(url));expect(save).toHaveBeenCalledWith(png,'deploy-check-benchmark.png');expect(await screen.findByRole('status')).toHaveTextContent('Upload it');});
it('does not open Instagram when saving is cancelled',async()=>{const backend=await show();vi.spyOn(backend,'saveImage').mockResolvedValue({ok:false,cancelled:true,error:'Cancelled'});const open=vi.spyOn(backend,'openUrl');await screen.findByAltText('Benchmark image for deploy-check');fireEvent.click(screen.getByRole('button',{name:'Instagram'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Instagram'})).toBeEnabled());expect(open).not.toHaveBeenCalled();});

it('offers icon-only circles and preserves dark appearance when switching to horizontal',async()=>{
 const backend=await show(),save=vi.spyOn(backend,'saveImage').mockResolvedValue({ok:true,value:undefined});await screen.findByAltText('Benchmark image for deploy-check');
 expect(screen.queryByText('Your benchmark as a PNG.')).toBeNull();
 for(const name of ['Reddit','X','Instagram','LinkedIn','Copy image','Save PNG']){const button=screen.getByRole('button',{name});expect(button).toHaveClass('skill-share-circle');expect(button.textContent).toBe('');expect(button).toHaveAttribute('title',name);}
 fireEvent.click(screen.getByRole('button',{name:'Dark'}));await waitFor(()=>expect(renderShareCard).toHaveBeenLastCalledWith(expect.anything(),{format:'dark'}));await screen.findByAltText('Benchmark image for deploy-check');
 fireEvent.click(screen.getByRole('button',{name:'Horizontal'}));await waitFor(()=>expect(renderShareCard).toHaveBeenLastCalledWith(expect.anything(),{format:'horizontal-dark'}));await screen.findByAltText('Benchmark image for deploy-check');
 fireEvent.click(screen.getByRole('button',{name:'Save PNG'}));await waitFor(()=>expect(save).toHaveBeenCalledWith(png,'deploy-check-benchmark-horizontal-dark.png'));
 fireEvent.click(screen.getByRole('button',{name:'Light'}));await waitFor(()=>expect(renderShareCard).toHaveBeenLastCalledWith(expect.anything(),{format:'horizontal'}));
});
