import type { LaunchContext, IdentityArgs, IdentityWrite, Settings, Onboarding, Features, Capabilities, Surfaces, ReadOptions, Catalog, ChangeSource, ConnectArgs, ConnectOutcome, EvalArgs, EvalResult, EvalReportModel, InboxItem, InstallArgs, InstalledResult, InviteArgs, InviteResult, MachineUninstallResult, PrefStore, PublishArgs, PublishResult, Receipt, Result, Roster, Run, LibraryScope, CheckoutAdded, CheckoutRemoved, ProjectCreated, SearchArgs, SearchHit, SetupArgs, SetupResult, Library, SkillDetail, StatusResult, Subscription, SyncArgs, SyncResult, TeamArgs, TeamResult, UninstallArgs, UninstalledResult, UpdateAdvice, ValidateArgs, ValidateResult } from './types';
export interface Backend {
  setWindowBackground(color: string): Promise<Result<void>>;
  quit(): Promise<void>;
  features(): Promise<Features>;
  windowAction(action: 'toggle-maximize' | 'start-drag'): Promise<Result<void>>;
  openUrl(url: string): Promise<Result<void>>;
  revealPath(path: string): Promise<Result<void>>;
  /** Native folder chooser. `null` is a cancelled dialog, not a failure. */
  pickFolder(): Promise<Result<string | null>>;
  capabilities(): Promise<Capabilities>;
  surfaces(): Promise<Surfaces>;
  launchContext(): Promise<LaunchContext | null>;
  refreshLaunch(): Promise<LaunchContext | null>;
  onLaunchRequest(listener: () => void): Subscription;
  status(q?: undefined, options?: ReadOptions): Promise<Result<StatusResult>>;
  settings(q?: undefined, options?: ReadOptions): Promise<Result<Settings>>;
  onboarding(q?: undefined, options?: ReadOptions): Promise<Result<Onboarding>>;
  library(q: { scope: LibraryScope; team?: string }, options?: ReadOptions): Promise<Result<Library>>;
  localSkill(q: { path: string }, options?: ReadOptions): Promise<Result<SkillDetail>>;
  checkouts: { add(path:string):Run<CheckoutAdded>; remove(path:string):Run<CheckoutRemoved> };
  /** Team projects (team.json), not the local checkout folders above: `create` names one and commits it to the team's main. */
  projects: { create(args:{name:string;remote?:string}):Run<ProjectCreated> };
  skill(q: { ref: string; team?: string }, options?: ReadOptions): Promise<Result<SkillDetail>>;
  evalReport(q: { ref: string; team?: string }, options?: ReadOptions): Promise<Result<EvalReportModel>>;
  receipts(q: { skillId: string; version: string }, options?: ReadOptions): Promise<Result<Receipt | null>>;
  inbox(q?: undefined, options?: ReadOptions): Promise<Result<InboxItem[]>>;
  catalog(q?: { q?: string }, options?: ReadOptions): Promise<Result<Catalog>>;
  roster(q?: undefined, options?: ReadOptions): Promise<Result<Roster>>;
  search(args: SearchArgs, options?: ReadOptions): Promise<Result<SearchHit[]>>;
  profile(args: { name?: string; bio?: string; role?: string; projects?: string[] }): Run<{ handle: string; changed: string[] }>;
  decline(args: { ref: string }): Run<{ id: string }>;
  setIdentity(args: IdentityArgs): Run<IdentityWrite>;
  install(args: InstallArgs): Run<InstalledResult[]>;
  uninstallSkill(args: UninstallArgs): Run<UninstalledResult[]>;
  uninstallMachine(args: Record<string, never>): Run<MachineUninstallResult>;
  connect(args: ConnectArgs): Run<ConnectOutcome | undefined>;
  publish(args: PublishArgs): Run<PublishResult>;
  sync(args: SyncArgs): Run<SyncResult>;
  invite(args: InviteArgs): Run<InviteResult>;
  team(args: TeamArgs): Run<TeamResult>;
  setup(args: SetupArgs): Run<SetupResult>;
  eval(args: EvalArgs): Run<EvalResult>;
  validate(args: ValidateArgs, options?: ReadOptions): Promise<Result<ValidateResult>>;
  update(q?: undefined, options?: ReadOptions): Promise<Result<UpdateAdvice>>;
  diagnostics(): Run<void>;
  openInEditor(path: string): Promise<Result<void>>;
  copyToClipboard(text: string): Promise<Result<void>>;
  copyImage(png: Blob): Promise<Result<void>>;
  readonly prefs: PrefStore;
  subscribe(listener: (source: ChangeSource) => void): Subscription;
}
