import { it, expect, afterEach, vi } from 'vitest';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Providers } from './providers';
import { usePrompter } from '../backend';
import type { Prompter } from '../backend/types';
afterEach(cleanup);
function PromptTrigger({ask,onResult}:{ask:(prompter:Prompter)=>Promise<string|boolean>;onResult:(value:string|boolean)=>void}){const prompter=usePrompter({});return <button onClick={()=>{void ask(prompter).then(onResult,error=>onResult(error instanceof Error?error.message:String(error)));}}>Ask</button>;}
it('opens a new dialog for an unexpected confirmation and resolves its answer',async()=>{const result=vi.fn();const user=userEvent.setup();render(<Providers><PromptTrigger ask={p=>p.confirm('Unplanned consent?')} onResult={result}/></Providers>);await user.click(screen.getByRole('button',{name:'Ask'}));expect(await screen.findByRole('dialog')).toHaveTextContent('Unplanned consent?');await user.click(screen.getByRole('button',{name:'Confirm'}));await waitFor(()=>expect(result).toHaveBeenCalledWith(true));});
it('collects text with its default and returns the edited value',async()=>{const result=vi.fn();const user=userEvent.setup();render(<Providers><PromptTrigger ask={p=>p.text('Workspace name','Terum')} onResult={result}/></Providers>);await user.click(screen.getByRole('button',{name:'Ask'}));const input=await screen.findByRole('textbox');expect(input).toHaveValue('Terum');await user.clear(input);await user.type(input,'Docs');await user.click(screen.getByRole('button',{name:'Continue'}));await waitFor(()=>expect(result).toHaveBeenCalledWith('Docs'));});
it('handles selecting a choice and cancelling a text prompt',async()=>{const result=vi.fn();const user=userEvent.setup();const view=render(<Providers><PromptTrigger ask={p=>p.select('Role',['Admin','Member'])} onResult={result}/></Providers>);await user.click(screen.getByRole('button',{name:'Ask'}));await user.selectOptions(await screen.findByRole('combobox'),'Member');await user.click(screen.getByRole('button',{name:'Continue'}));await waitFor(()=>expect(result).toHaveBeenCalledWith('Member'));view.rerender(<Providers><PromptTrigger ask={p=>p.text('Name')} onResult={result}/></Providers>);await user.click(screen.getByRole('button',{name:'Ask'}));await user.click(await screen.findByRole('button',{name:'Cancel'}));await waitFor(()=>expect(result).toHaveBeenCalledWith('Cancelled.'));});
