import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import type { Theme } from '../backend/types';
export function applyTheme(theme:Theme):void {
 const resolved=theme==='system'?(typeof matchMedia==='function'&&matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):theme;
 document.documentElement.dataset.theme=resolved;
 try{localStorage.setItem('terum-theme',resolved);}catch{ /* Theme remains usable in memory when browser storage is denied. */ }
}
interface UiState {theme:Theme;sidebarCollapsed:boolean;overviewHidden:boolean;railOpen:boolean;lastRoute:string;setTheme:(theme:Theme)=>void;setOverviewHidden:(hidden:boolean)=>void;setRailOpen:(open:boolean)=>void;setLastRoute:(route:string)=>void}
export const useUiStore=create<UiState>()(persist(set=>({theme:'dark',sidebarCollapsed:false,overviewHidden:false,railOpen:true,lastRoute:'/library/global',setTheme:theme=>{applyTheme(theme);set({theme});},setOverviewHidden:overviewHidden=>set({overviewHidden}),setRailOpen:railOpen=>set({railOpen}),setLastRoute:lastRoute=>set({lastRoute})}),{name:'terum-skills-app:ui',merge:(persisted,current)=>{if(!persisted||typeof persisted!=='object')return current;const saved=persisted as Record<string,unknown>;return {...current,theme:saved.theme==='dark'||saved.theme==='light'||saved.theme==='system'?saved.theme:current.theme,sidebarCollapsed:typeof saved.sidebarCollapsed==='boolean'?saved.sidebarCollapsed:current.sidebarCollapsed,overviewHidden:typeof saved.overviewHidden==='boolean'?saved.overviewHidden:current.overviewHidden,railOpen:typeof saved.railOpen==='boolean'?saved.railOpen:current.railOpen,lastRoute:typeof saved.lastRoute==='string'&&saved.lastRoute.startsWith('/')?saved.lastRoute:current.lastRoute};},storage:createJSONStorage(()=>({getItem:key=>{try{return localStorage.getItem(key);}catch{return null; /* Default state remains usable without storage. */}},setItem:(key,value)=>{try{localStorage.setItem(key,value);}catch{ /* State still persists for this mounted session. */ }},removeItem:key=>{try{localStorage.removeItem(key);}catch{ /* In-memory state is unaffected by unavailable storage. */ }}}))}));
