import { useState } from 'react';
import type { ReactNode } from 'react';
import { Dialog, DialogPopup, DialogTitle } from '../../components/ui/Dialog';
import { useSearchParams, useNavigate } from 'react-router';
import { useBackend, useCapabilities, cloneStateCopy } from '../../backend';
import type { IdentityArgs, Settings, StatusResult, Theme, UpdateAdvice } from '../../backend/types';
import { useUiStore } from '../../app/store';
import { RichText, TerminalHint } from '../../components/domain/Primitives';
import { InlineChoice, WorkflowDialog, WorkflowField } from '../../components/domain/WorkflowControls';
import { useWorkflow } from '../../components/domain/useWorkflow';
import { WorkflowPopup } from '../../components/domain/WorkflowPopup';
import { Button } from '../../components/ui/Button';
import { Switch } from '../../components/ui/Switch';
import { Chip } from '../../components/ui/Chip';
import { Kbd } from '../../components/ui/Kbd';
import { SettingsHead as Head, SettingRow as Row, SettingCard as Card, SettingsGroup as Group, SettingsNote as Note, Mono, Value, LockedValue, StatusValue } from './SettingsParts';
import { SettingsDialogs } from './SettingsDialogs';
import { inboxLabels, settingsRows } from './settings-data';

type Props={section:string;data:Settings;status:StatusResult;report:UpdateAdvice|null;updateError:string|null;appVersion:string|null};
export function SettingsContent({section,data:d,status,report,updateError,appVersion}:Props){
  const backend=useBackend(),capabilities=useCapabilities(),action=useWorkflow(),[search,setSearch]=useSearchParams(),navigate=useNavigate();
  const [signIn,setSignIn]=useState(false);
  const [identityDraft,setIdentityDraft]=useState<IdentityArgs>({});
  const [identityBase,setIdentityBase]=useState<IdentityArgs>({});
  const [identityDirty,setIdentityDirty]=useState<Partial<Record<keyof IdentityArgs,boolean>>>({});
  const [identityNotice,setIdentityNotice]=useState<string|null>(null);
  const theme=useUiStore(s=>s.theme),setTheme=useUiStore(s=>s.setTheme);
  const closeUpdate=()=>setSearch(p=>{p.delete('dialog');return p;});
  const rows=settingsRows.parse(d);
  const me=status.me,machine=status.machine,team=status.teams[0];
  function open(command:string){void action.open(command);}
  function sync(){void action.run(()=>backend.sync({}));}
  function dialog(name:string){setSearch(p=>{p.set('dialog',name);return p;});}
  function prune(){if(section==='machine')dialog('prune');else navigate('/settings/machine?dialog=prune'+(search.get('__mock')?'&__mock='+search.get('__mock'):''));}
  const toggle=(key:string,label:string,fallback=true)=><span className="settings-toggle-hit"><Switch aria-label={label} checked={backend.prefs.get(key,fallback)} onCheckedChange={value=>action.pref(key,value)}/></span>;
  const field=(key:keyof IdentityArgs,label:string,fallback:string)=><WorkflowField aria-label={label} style={{width:260}} value={identityDirty[key]||identityBase[key]===fallback?identityDraft[key]??fallback:fallback} disabled={action.busy} onChange={event=>{setIdentityBase(current=>({...current,[key]:fallback}));setIdentityDraft(current=>({...current,[key]:event.target.value}));setIdentityDirty(current=>({...current,[key]:true}));}} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();}} onBlur={()=>{
    const value=identityDraft[key];
    if(value===undefined||value===fallback||!identityDirty[key]||action.busy)return;
    void action.run(()=>backend.setIdentity({[key]:value}),{},result=>{
      setIdentityNotice(result.notice);
      const saved=result.updated.find(item=>item.key===(key==='defaultHandle'?'default-handle':key));
      if(saved){setIdentityDraft(current=>({...current,[key]:saved.value}));setIdentityDirty(current=>({...current,[key]:false}));}
    });
  }}/>;
  const choice=(key:string,label:string,fallback:string,options:string[])=><InlineChoice label={label} value={backend.prefs.get(key,fallback)} options={options} onChange={value=>action.pref(key,value)}/>;
  const finder=(path:string)=><Button kind="ghost" icon="folder" onClick={()=>void action.perform(()=>backend.revealPath(path))}>Show in Finder</Button>;
  let content:ReactNode;
  switch(section){
    case 'teams': content=<><Head title="Teams" sub="The teams this machine is configured for, and what each team decided for everyone."/>
      <Group label="Configured here" note={team&&<TerminalHint command={`npx -y terum-skills@latest team leave ${team.key}`} prefix="Leave stands for"/>}><Card>{team?<>
        <Row title={team.name} desc={`${team.remote??'—'} · ${team.members??'—'} members · ${team.skills??'—'} shared skills`}><Value mono>handle {team.handle}</Value></Row>
        <Row title="Clone" desc={team.cloneState?cloneStateCopy(team.cloneState,team.clone??'—',team.remote??'—',team.readable??true):"The working copy sync pulls. Safe to delete; the next sync clones it again."}><Value mono>{team.clone??'—'}</Value></Row>
        <Row title="Last sync" desc={`${syncTime(team.last_sync)} · stamp ${team.stamp??'—'}`}><Button icon="refresh" onClick={sync} disabled={action.busy}>Sync now</Button></Row>
        <Row title="Leave on this machine" desc="Removes its placed skills, the clone and this entry here, and the session-start hook when this was the last team. You stay a member; run setup again to come back."><Button kind="danger" state={search.get('dialog')==='leave'?'pressed':'default'} onClick={()=>dialog('leave')}>Leave</Button></Row>
      </>:<Row title="No teams configured"/>}</Card></Group>
      <Group label="Join" note={<TerminalHint command="npx -y terum-skills@latest setup <org>/<repo>"/>}><Card><Row title="Join another team" desc="Paste the block a teammate sent you, or run it in a terminal. Your default handle is offered; a collision asks for another."><Button icon="user-plus" onClick={()=>open('npx -y terum-skills@latest setup <org>/<repo>')}>Join</Button></Row></Card></Group>
      <Group label="Team policy · read only" note={<Note>Team policy lives in team.json. It changes by a pull request on GitHub; the app has no verb for it.</Note>}><Card>
        <Row title="Categories" desc={d.TEAM_POLICY.categoriesNote}><div className="settings-chips">{team?.categories?.map(name=><Chip key={name}>{name}</Chip>)??<Value quiet>—</Value>}</div></Row>
        <Row title="Publishing" desc="Endorsing a skill to a team list opens a pull request; the merge is the review."><Value>{d.TEAM_POLICY.publish??'—'}</Value></Row>
        <Row title="Skill license" desc="Injected into every shared SKILL.md."><Value mono>{d.TEAM_POLICY.license??'—'}</Value></Row>
        <Row title="Projects" desc="Name → repository. A project's skills place when you sync inside its checkout."><Value quiet>{d.TEAM_POLICY.projects?.join(' · ')??'—'}</Value></Row>
      </Card></Group></>;break;
    case 'machine': content=<><Head title="This machine" sub="What Terum put on this laptop, and what it will ask you again for on the next one."/>
      <Group label="Identity"><Card><Row title={machine.name} desc={`${machine.os} · the name in the footer. Terum keeps no list of your machines and nothing here is committed.`}><Value quiet>This machine</Value></Row>{capabilities?.machineRegistry?<Row title="Other machines" desc="Nothing to list. Your installs are recorded in your people file and placed by sync on whichever machine runs it; tool approvals are asked again there."><Value quiet>—</Value></Row>:null}</Card></Group>
      <Group label="Placed here" note={<Note>The provenance ledger: the only paths Terum may ever touch. Tracked copies follow the team at sync; a pinned one stays until you install again.</Note>}><div className="placement-table" role="table" aria-label="Placed here"><div className="placement-head" role="row">{['Path','Scope','Version','Placed','State'].map(text=><span role="columnheader" key={text}>{text}</span>)}</div>{rows.PLACEMENTS.map(([path,skill,scope,version,placed,state],index)=><div role="row" className="placement-row" data-testid={'placement-row-'+index} key={path}><span role="cell" title={skill}>{path}</span><span role="cell">{scope}</span><span role="cell" className="board-mono" style={{color:version?'var(--tk-text1)':'var(--tk-text3)'}}>{version??'tracking'}</span><span role="cell">{placed}</span><span role="cell">{state}</span></div>)}<div className="placement-footer">{d.PLACEMENTS_N} placed · {status.counts.Global??'—'} global · {d.PINNED_N} pinned</div></div></Group>
      <Group label="Tool approvals on this machine" note={<Note>An approval covers exactly these tools. A changed or widened set asks again; there is no way to revoke one yet.</Note>}><Card>{rows.APPROVALS.map(([skill,grants,approved])=><Row key={skill} title={skill} desc={`Approved ${approved}`}><div className="settings-chips" style={{maxWidth:320}}>{grants.map(grant=><Chip key={grant}>{grant}</Chip>)}</div></Row>)}<Row title="Other skills" desc="Declare no tools and place without asking."><Value quiet>No approval needed</Value></Row></Card></Group>
      <Group label="Quarantine" trailing={<Button icon="trash" onClick={prune} state={search.get('dialog')==='prune'?'pressed':'default'}>Prune…</Button>} note={<TerminalHint command="npx -y terum-skills@latest sync --prune" prefix="Prune stands for"/>}><Card>{rows.QUARANTINE.map(([when,name,why,size])=><Row key={when+name} title={name} desc={`${why} · ${when}`}><Value quiet>{size}</Value></Row>)}</Card></Group></>;break;
    case 'sync': {const hook=backend.prefs.get('sync:hook',d.HOOK.installed);content=<><Head title="Sync" sub="How this machine follows the team, and what it will never do without you."/>
      <Group label="Session-start hook"><Card><Row title="Sync at session start" desc={hook?<>Installed in <Mono>{d.HOOK.file}</Mono> · runs <Mono>npx -y terum-skills@latest sync --hook</Mono> in the background, at most once an hour per team.</>:"Not installed. Run sync yourself, or turn this on to add the entry to ~/.claude/settings.json."}>{toggle('sync:hook','Sync at session start',d.HOOK.installed)}</Row><Row title="What it places without asking" desc="Updates whose tool grants have not changed, and skills that grant no tools. A new or widened grant waits in your Inbox until you approve it."/><Row title="Local edits to a placed copy" desc="Overwritten at sync and moved to quarantine, so nothing is lost and nothing stays stale."/></Card></Group>
      <Group label="On demand" note={<TerminalHint command="npx -y terum-skills@latest sync" prefix="Sync now stands for"/>}><Card><Row title="Sync now" desc={`Last sync ${syncTime(team?.last_sync??null)} · ${team?.name??'—'}. One sync covers every team; an unreachable one is skipped and reported.`}><Button icon="refresh" onClick={sync} disabled={action.busy}>Sync now</Button></Row>{status.teams.filter(team=>team.pending.length>0).map(team=><Row key={team.key} title={team.name} desc="Work left undone; run sync"/>)}{d.syncNote&&<Row title="Sync timestamps" desc={d.syncNote}/>}<Row title="Quarantine" desc={`${d.QUARANTINE.length} folders · ${d.STORAGE.quarantine}. Only prune deletes here, after listing every path.`}><Button icon="trash" onClick={prune}>Prune…</Button></Row></Card></Group></>;break;}
    case 'updates': content=<><Head title="Updates" sub="Skills follow the team unless pinned; the CLI tells you about a release and never installs it for you."/>
      <Group label="Skills"><Card><Row title="Tracked installs" desc={`Re-placed at sync when the team copy changes. ${d.PLACEMENTS_N} placements on this machine.`}><Value quiet>Follow the team</Value></Row><Row title="Pinned installs" desc={`Installed at a version; they never move until you install again. ${d.PINNED_N} on this machine.`}><Value quiet>Stay put</Value></Row><Row title="Update notices" desc="An update lands in Inbox ▸ Updates when a tracked skill changed and could not be placed silently.">{toggle('updates:notices','Update notices')}</Row></Card></Group>
      <Group label="The CLI" note={<TerminalHint command="npx -y terum-skills@latest update" prefix="Prints the command, never runs it"/>}><Card><Row title="terum-skills" desc={report?.description??'—'}><Button onClick={()=>dialog('update')}>Show update command</Button></Row><Row title="Release notice" desc="One line after a command when a newer release is advertised or observed, at most once a day per release. Silenced by the CI, NO_UPDATE_NOTIFIER or TERUM_SKILLS_NO_UPDATE_NOTIFIER environment variables, not from here."><Value quiet>On</Value></Row><Row title="Release probe" desc="Reads release tags from github.com/ryanliu-terum/terum-skills on an interactive sync, at most once a day, and whenever you run update — never from the session hook or a prune, and only while a team on this machine lives on GitHub. It runs no package manager and makes no registry request; a copy launched with npx also reads that cache's @latest entry, which can be the newer of the two."><Value quiet>GitHub tags</Value></Row></Card></Group>
      <Group label="The app"><Card><Row title="Terum Skills app" desc={`${appVersion??'—'} · no update channel yet.`}><Value quiet>—</Value></Row></Card></Group></>;break;
    case 'inbox': content=<><Head title="Inbox" sub="Which kinds of news reach you, and how the sidebar shows them."/><Group label="Kinds"><Card>{Object.entries(d.INBOX_KIND_TEXT).filter(([key])=>capabilities?.offtargetKind||(key!=='alert'&&key!=='offtarget')).map(([key,desc])=><Row key={key} title={inboxLabels[key]??key} desc={desc}><span className="settings-toggle-hit"><Switch role="checkbox" aria-label={inboxLabels[key]??key} checked={backend.prefs.get('inbox:kind:'+key,true)} onCheckedChange={value=>action.pref('inbox:kind:'+key,value)}/></span></Row>)}</Card></Group>
      <Group label="Sidebar and bell"><Card><Row title="Sidebar rows" desc="How the sidebar groups the list under Inbox.">{choice('inbox:sidebar','Sidebar rows','Pushes · Updates · Alerts',['Pushes · Updates · Alerts'])}</Row><Row title="Badge on the bell" desc="Unread count in the top bar.">{toggle('inbox:badge','Badge on the bell')}</Row></Card></Group>
      <Group label="People" note={<Note>Follows are kept by this app on this machine. The team repo has no place for them yet, so another machine starts from nothing.</Note>}><Card><Row title="Following" desc="Follow someone from their card in the Marketplace; their new skills then land here."><Value quiet={!d.FOLLOWING.length}>{d.FOLLOWING.length?d.FOLLOWING.join(', '):'Nobody yet'}</Value></Row></Card></Group></>;break;
    case 'evals': {const k='K' in d&&typeof d.K==='number'?String(d.K):'—';content=<><Head title="Evals" sub="The defaults a run starts from, and what an eval needs on this machine."/>
      <Group label="Defaults" note={<Note>These are the flags the app passes to <Mono>npx -y terum-skills@latest eval &lt;skill&gt; --k 3 --model sonnet</Mono>. The CLI keeps no defaults of its own.</Note>}><Card><Row title="Repetitions per case" desc={`k = ${k} gates on the verdict band alone; k = 10 for a receipt whose sign test means something.`}>{choice('eval:k','Repetitions per case',k,k==='—'?['—','1','3','5','10']:['1','3','5','10'])}</Row><Row title="Model for the arms" desc="Every number on one surface comes from one model; the Library names it beside the counts.">{choice('eval:model','Model for the arms','sonnet',['sonnet'])}</Row><Row title="Judge" desc="Asked twice, in both orderings; a disagreement is a tie.">{choice('eval:judge','Judge','sonnet',['sonnet'])}</Row><Row title="Escalation judge" desc="For a split judge. Named in the spec; the CLI does not take it yet."><Value quiet>opus · not yet</Value></Row></Card></Group>
      <Group label="On this machine"><Card><Row title="Agent CLI" desc="Evals drive the claude CLI on this machine, on your own subscription. No cap on spend exists; the estimate before a run is the only guard."><StatusValue>{d.AGENT_CLI} · signed in</StatusValue></Row><Row title="Sandbox" desc="Each arm runs with project-scoped settings only, so your global skills cannot leak into a result."><Value mono>--setting-sources project</Value></Row><Row title="Run trees" desc={`evals/${team?.key??'—'} · ${d.STORAGE.evals_n} runs · ${d.STORAGE.evals}, transcripts included. Nothing prunes these.`}>{team&&finder(`~/.terum/skills/evals/${team.key}`)}</Row><Row title="Commit receipts" desc="A finished run is committed to the team repo as one immutable file, after secret redaction.">{toggle('eval:commit','Commit receipts')}</Row></Card></Group></>;break;}
    case 'sharing': content=<><Head title="Sharing" sub="The skills you author on this machine, and how they reach the team."/>
      <Group label="Shared from this machine" note={<TerminalHint command={'npx -y terum-skills@latest connect ~/.claude/skills/'+(d.LOCAL_UNSHARED[0]??'<skill>')} prefix="Share stands for"/>}><Card>{rows.SHARED.map(([name,source,teamName,state])=><Row key={name} title={name} desc={source+' · '+teamName}>{state==='In sync'?<StatusValue>In sync</StatusValue>:state==='Local edit'?<StatusValue>Local edit · commits at next sync</StatusValue>:state==='Diverged'?<><StatusValue kind="warn">Diverged</StatusValue><Button kind="ghost" onClick={()=>open('npx -y terum-skills@latest share '+source)}>Keep mine</Button><Button kind="ghost" onClick={()=>open('npx -y terum-skills@latest share '+source)}>Keep the team's</Button></>:<Value quiet>{state}</Value>}</Row>)}{d.LOCAL_UNSHARED.map(name=><Row key={name} title={name} desc={'~/.claude/skills/'+name}><Value quiet>Not shared</Value><Button icon="upload" onClick={()=>void action.run(()=>backend.connect({path:'~/.claude/skills/'+name}))}>Share</Button></Row>)}</Card></Group>
      <Group label="Rules"><Card><Row title="Frontmatter" desc="connect adds license, id and author to your SKILL.md, after showing the three lines and asking."/><Row title="Privileged folders" desc="A skill carrying .claude-plugin/ or hook definitions is refused unless you pass --allow-privileged."/><Row title="Later edits" desc="Flow to the team at sync. When both sides changed, nothing moves until you pick a side."/><Row title="Share card" desc="A PNG with the install line, for Slack. Not available yet."><Value quiet>—</Value></Row></Card></Group></>;break;
    case 'appearance': content=<><Head title="Appearance" sub="This app&#39;s own preferences. They live with the app, not in the team or in ~/.terum."/><Group label="Look"><Card><Row title="Theme" desc="Follow the system, or a fixed theme."><div className="settings-theme" role="group" aria-label="Theme">{d.THEME_OPTIONS.map(label=><button key={label} type="button" aria-pressed={theme===label.toLowerCase()} onClick={()=>{const value=label.toLowerCase();if(value==='dark'||value==='light'||value==='system'){setTheme(value as Theme);if(search.has('theme'))setSearch(p=>{p.set('theme',value);return p;});}}}>{label}</button>)}</div></Row><Row title="Open at start">{choice('appearance:start','Open at start','Library ▸ Global',['Library ▸ Global'])}</Row><Row title="Sidebar counts" desc="Skill counts beside each list and unread counts under Inbox.">{toggle('appearance:counts','Sidebar counts')}</Row><Row title="Machine name in the footer">{toggle('appearance:machine','Machine name in the footer')}</Row></Card></Group><Group label="Keyboard"><Card>{rows.SHORTCUTS.map(([label,key])=><Row key={label} title={label}><Kbd>{key}</Kbd></Row>)}</Card></Group></>;break;
    case 'advanced': content=<><Head title="Advanced" sub="Where things live on this machine, diagnostics, and the two things that cannot be undone from here."/>
      <Group label="Local state"><Card><Row title="Local state" desc="~/.terum/skills · config, team clones, cache, quarantine, run stamps, eval runs. Nothing in it is team truth. The clones, cache and run stamps are disposable — setup and team join rebuild them. config.json is not: delete it and every skill Terum placed goes invisible to the tool (no ledger entry, so sync neither refreshes nor adopts those folders and install refuses their targets until you re-install each one with --force), every tool approval is asked again, every connected skill's baseline is lost, and your handle, email and display name are re-asked.">{finder('~/.terum/skills')}</Row><Row title="Pinned checkouts" desc={`cache/${team?.key??'—'} · ${d.STORAGE.cache_n} versions`}><Value quiet>{d.STORAGE.cache}</Value></Row><Row title="Eval runs" desc={`evals/${team?.key??'—'} · ${d.STORAGE.evals_n} runs, transcripts included. Nothing prunes these.`}><Value quiet>{d.STORAGE.evals}</Value></Row></Card></Group>
      <Group label="Diagnostics" note={<TerminalHint command="npx -y terum-skills@latest status" prefix="Run stands for"/>}><Card><Row title="Status" desc="Prints each team's clone state, roster and counts, and how stale the last sync is."><Button icon="terminal" onClick={()=>open('npx -y terum-skills@latest status')}>Run</Button></Row><Row title="Logs" desc="The CLI prints as it goes and keeps no log file. Copy a command's output from the terminal."><Value quiet>—</Value></Row></Card></Group>
      <Group label="Danger zone" note={<TerminalHint command="npx -y terum-skills@latest uninstall" prefix="Remove stands for"/>}><Card><Row title="Session-start hook" desc="Removed with your last team, or by the removal below; there is no separate switch."/><Row title="Remove terum-skills from this machine" desc="Every team you joined here: placed skills, clones, cache, the session hook. A record is written to backups/ first. Your people files in the team repos are untouched."><Button kind="danger" disabled={action.busy} onClick={()=>void action.run(()=>backend.uninstallMachine({}),{'Remove terum-skills from this machine?':false})}>Remove…</Button></Row></Card></Group></>;break;
    case 'about': content=<><Head title="About" sub=""/><Group label="Versions" note={<TerminalHint command="npx -y terum-skills@latest update" prefix="Check stands for"/>}><Card><Row title="Terum Skills app"><Value>{d.APP_VERSION}</Value></Row><Row title="terum-skills CLI" desc={`${d.CLI_LATEST} available`}><Value>{d.CLI_VERSION}</Value><Button kind="ghost" icon="refresh" onClick={()=>open('npx -y terum-skills@latest update')}>Check</Button></Row><Row title="Agent CLI"><Value>{d.AGENT_CLI}</Value></Row><Row title="Platform"><Value>{machine.os}</Value></Row></Card></Group><Group label="Project"><Card><Row title="Feedback and requests"><a href={'https://'+d.COMMUNITY} onClick={e=>{e.preventDefault();void action.perform(()=>backend.openUrl('https://'+d.COMMUNITY));}}>{d.COMMUNITY}</a></Row><Row title="License" desc="The tool is Apache-2.0. The team's skills stay in the team's own repository."><Value>Apache-2.0</Value></Row></Card></Group></>;break;
    default: content=<><Head title="Account" sub="Who you are to GitHub and to the team."/>
      <Group label="GitHub"><Card><Row title="GitHub" desc="Tool presence only; authentication is not checked. Creating a team or inviting needs gh; joining and syncing use the git credentials this machine already has.">{status.tools.git&&status.tools.gh?<StatusValue>git present · gh present</StatusValue>:<Value quiet>{`${status.tools.git?'git present':'git absent'} · ${status.tools.gh?'gh present':'gh absent'}`}</Value>}<Button kind="ghost" icon="external-link" onClick={()=>setSignIn(true)}>Open gh</Button></Row><Row title="Access to team repos" desc="gh signs the API calls; git pulls and pushes with your existing credentials. Terum stores no token of its own, and a token an older version stored is ignored."><Value quiet>Ambient git credentials</Value></Row></Card></Group>
      <Group label="Identity" note={<Note>These form the author line on every skill you share: <Mono>{me.name} &lt;{me.email}&gt;</Mono>. Changing them rewrites that line at the next sync.</Note>}><Card><Row title="Name">{field('name','Name',d.ME.name)}</Row><Row title="Email">{field('email','Email',d.ME.email)}</Row><Row title="Default handle" desc="Suggested whenever you join a team.">{field('defaultHandle','Default handle',d.ME.default_handle)}</Row><Row title={`Handle on ${team?.name??'—'}`} desc="Fixed once your people file exists. A second team can use a different one."><LockedValue>{me.handle}</LockedValue></Row></Card></Group>
      <Group label="Session" note={<TerminalHint command="gh auth logout" prefix="From the terminal"/>}><Card><Row title="Sign out" desc="Signs gh out on this machine. Terum has no account of its own, so nothing else changes."><Button onClick={()=>open('gh auth logout')}>Sign out</Button></Row></Card></Group></>;
  }
  return <>{content}{identityNotice?<Dialog open onOpenChange={open=>{if(!open)setIdentityNotice(null);}}><WorkflowPopup><DialogTitle>Identity saved</DialogTitle><div role="status">{identityNotice}</div><Button onClick={()=>setIdentityNotice(null)}>Close</Button></WorkflowPopup></Dialog>:null}{section==='updates'&&search.get('dialog')!=='update'&&updateError&&<div role="alert" className="settings-action-error">{updateError}</div>}{section==='updates'&&search.get('dialog')==='update'&&<Dialog open onOpenChange={open=>{if(!open)closeUpdate();}}><DialogPopup><DialogTitle>Update command</DialogTitle>{report?<pre className="board-mono" style={{whiteSpace:'pre-wrap'}}>{report.advice.join('\n')}</pre>:<p role={updateError?'alert':'status'}>{updateError??'Loading update advice…'}</p>}<Button onClick={closeUpdate}>Close</Button></DialogPopup></Dialog>}{signIn?<WorkflowDialog title="Sign in from a terminal" body="Run gh auth login in a terminal, then return here and try again. This app does not change your credentials." primary="Copy command" command="gh auth login" close={()=>setSignIn(false)} submit={()=>void action.perform(()=>backend.copyToClipboard('gh auth login'))} busy={action.busy} error={action.error}/>:null}{action.error&&<div role="alert" className="settings-action-error"><RichText text={action.error}/></div>}<SettingsDialogs section={section} data={d} status={status}/></>;
}

function syncTime(value:string|null):string {
 if(value===null)return 'No sync recorded on this machine';
 if(!/^\d{4}-\d{2}-\d{2}T/.test(value))return value;
 const minutes=Math.round((Date.now()-Date.parse(value))/60000);
 return new Intl.RelativeTimeFormat('en',{numeric:'always'}).format(-minutes,'minute');
}
