import { useMachineRemoval } from '../../app/machine-removal-context';
import { plural } from '../marketplace/market-data';
import { relativeTime } from '../../lib/relative-time';
import { useState } from 'react';
import type { ReactNode } from 'react';
import { Dialog, DialogPopup, DialogTitle } from '../../components/ui/Dialog';
import { useSearchParams, useNavigate } from 'react-router';
import { useBackend, useFeatures, useCapabilities, cloneStateCopy } from '../../backend';
import type { IdentityArgs, Settings, StatusResult, Surfaces, Theme, UpdateAdvice } from '../../backend/types';
import { useUiStore } from '../../app/store';
import { RichText, TerminalHint } from '../../components/domain/Primitives';
import { InlineChoice, WorkflowDialog, WorkflowField } from '../../components/domain/WorkflowControls';
import { useSyncAction } from '../../components/domain/useSyncAction';
import { useWorkflow } from '../../components/domain/useWorkflow';
import { WorkflowPopup } from '../../components/domain/WorkflowPopup';
import { Button } from '../../components/ui/Button';
import { Switch } from '../../components/ui/Switch';
import { Chip } from '../../components/ui/Chip';
import { Kbd } from '../../components/ui/Kbd';
import { SettingsHead as Head, SettingRow as Row, SettingCard as Card, SettingsGroup as Group, SettingsNote as Note, Mono, Value, LockedValue, StatusValue } from './SettingsParts';
import { SettingsDialogs } from './SettingsDialogs';
import { AppUpdateRows } from './AppUpdateRows';
import { inboxLabels, settingsRows } from './settings-data';

type Props={surfaces:Surfaces|undefined;section:string;data:Settings;status:StatusResult;report:UpdateAdvice|null;updateError:string|null;appVersion:string|null};
export function SettingsContent({surfaces,section,data:d,status,report,updateError,appVersion}:Props){
  const backend=useBackend(),features=useFeatures(),capabilities=useCapabilities(),action=useWorkflow(),[search,setSearch]=useSearchParams(),navigate=useNavigate();
  const removal=useMachineRemoval();
  const syncAction=useSyncAction();
  const [projectPath,setProjectPath]=useState('');
  function add(){void action.run(()=>backend.projects.add(projectPath.trim()),{},()=>setProjectPath(''));}
  const [signIn,setSignIn]=useState(false),[signOut,setSignOut]=useState(false);
  const [identityDraft,setIdentityDraft]=useState<IdentityArgs>({});
  const [identityBase,setIdentityBase]=useState<IdentityArgs>({});
  const [identityDirty,setIdentityDirty]=useState<Partial<Record<keyof IdentityArgs,boolean>>>({});
  const [identityNotice,setIdentityNotice]=useState<string|null>(null);
  const theme=useUiStore(s=>s.theme),setTheme=useUiStore(s=>s.setTheme);
  const closeUpdate=()=>setSearch(p=>{p.delete('dialog');return p;});
  const rows=settingsRows.parse(d);
  const me=status.me,machine=status.machine,team=status.teams[0]; // one team per machine — legacy 2+ shows a hint, not a projection
  function sync(){syncAction.open();}
  function dialog(name:string,teamKey?:string){setSearch(p=>{p.delete('team');p.set('dialog',name);if(teamKey)p.set('team',teamKey);return p;});}
  function prune(){if(section==='machine')dialog('prune');else navigate('/settings/machine?dialog=prune'+(search.get('__mock')?'&__mock='+search.get('__mock'):''));}
  const toggle=(key:string,label:string,fallback=true)=><span className="settings-toggle-hit"><Switch aria-label={label} checked={backend.prefs.get(key,fallback)} onCheckedChange={value=>action.pref(key,value)}/></span>;
  const field=(key:keyof IdentityArgs,label:string,fallback:string)=><WorkflowField aria-label={label} style={{width:260}} value={identityDirty[key]||identityBase[key]===fallback?identityDraft[key]??fallback:fallback} disabled={action.busy} onChange={event=>{setIdentityBase(current=>({...current,[key]:fallback}));setIdentityDraft(current=>({...current,[key]:event.target.value}));setIdentityDirty(current=>({...current,[key]:true}));}} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();}} onBlur={()=>{
    const value=identityDraft[key];
    if(value===undefined||value===fallback||!identityDirty[key]||action.busy)return;
    void action.run(()=>backend.setIdentity({[key]:value}),{},result=>{
      setIdentityNotice(result.notice);
      const saved=result.updated.find(item=>item.key===(key==='defaultHandle'?'default-handle':key));
      if(saved){setIdentityDraft(current=>({...current,[key]:saved.value}));setIdentityDirty(current=>({...current,[key]:false}));}
    });
  }}/>;
  const choice=(key:string,label:string,fallback:string,options:string[])=><InlineChoice label={label} value={backend.prefs.get(key,fallback)} options={options} onChange={value=>action.pref(key,value)}/>;
  const finder=(path:string)=><Button kind="ghost" icon="folder" onClick={()=>void action.perform(()=>backend.revealPath(path))}>Show in Finder</Button>;
  // A supplied ledger is exhaustive; the design can supply only specimen placement rows.
  const trackedN=status.ledger?d.PLACEMENTS_N-d.PINNED_N:d.PLACEMENTS_N;
  const appUpdateMode:'none'|'notice'|'full'=surfaces?.appUpdate!==true?'none':features?.appUpdate?'full':'notice';
  const updateSummary=`${report?.running??'—'} installed · ${report?.observation==='same'?'up to date':report?.observation==='newer'&&report.latest?report.latest+' available':report?.observation==='older'&&report.latest?'newer than the advertised '+report.latest:'latest unknown'}`;
  let content:ReactNode;
  switch(section){
    case 'teams': content=<><Head title="Team" sub="Your team on this machine, and what it decided for everyone."/>
      <Group label="Configured here" note={status.teams.length===1&&team&&<TerminalHint command={`npx -y terum-skills@latest team leave ${team.key}`} prefix="Leave stands for"/>}>{status.teams.map(team=><Card key={team.key}>
        <Row title={team.name} desc={`${team.remote??'—'} · ${team.members===null?'— members':plural(team.members,'member')} · ${team.skills??'—'} shared skills`}><Value mono>handle {team.handle}</Value></Row>
        <Row title="Clone" desc={team.cloneState?cloneStateCopy(team.cloneState,team.clone??'—',team.remote??'—',team.readable??true):"The working copy sync pulls. Safe to delete; the next sync clones it again."}><Value mono>{team.clone??'—'}</Value></Row>
        <Row title="Last fetch" desc={`${syncTime(team.last_sync,!!status.ledger)} · stamp ${team.stamp??'—'}`}><Button icon="refresh" onClick={sync} disabled={action.busy}>Sync now</Button></Row>
        <Row title="Leave on this machine" desc="Removes its placed skills, the clone and this entry here, and the session-start hook. You stay a member; run setup again to come back."><Button kind="danger" state={search.get('dialog')==='leave'&&(search.get('team')===team.key||!search.has('team')&&status.teams.length===1)?'pressed':'default'} onClick={()=>dialog('leave',team.key)}>Leave</Button></Row>
      </Card>)}{status.teams.length===0&&<Card><Row title="No team on this machine"><Button onClick={()=>dialog('join')}>Set up a team</Button></Row></Card>}</Group>
      <Group label="Join" note={status.teams.length===0&&<TerminalHint command="npx -y terum-skills@latest setup <org>/<repo>"/>}><Card><Row title="Join another team" desc={status.teams.length===1?`Terum Skills keeps one team per machine. Leave ${team?.name} first, then join.`:status.teams.length>1?'Leave the teams you no longer want first':'Paste the block a teammate sent you. Your default handle is offered; a collision asks for another.'}>{status.teams.length===1&&team?<Button onClick={()=>dialog('leave',team.key)}>Leave {team.name} first</Button>:status.teams.length===0?<Button icon="user-plus" onClick={()=>dialog('join')}>Join</Button>:null}</Row></Card></Group>
      <Group label="Team policy · read only" note={<Note>Team policy lives in team.json. It changes by a pull request on GitHub; the app has no verb for it.</Note>}><Card>
        <Row title="Categories" desc={d.TEAM_POLICY.categoriesNote}><div className="settings-chips">{(status.teams.length===1?team?.categories:null)?.map(name=><Chip key={name}>{name}</Chip>)??<Value quiet>—</Value>}</div></Row>
        <Row title="Skill license" desc="Injected into every shared SKILL.md."><Value mono>{d.TEAM_POLICY.license??'—'}</Value></Row>
        <Row title="Projects" desc="Name → repository. A project's skills place when you sync inside its checkout."><Value quiet>{d.TEAM_POLICY.projects?.join(' · ')??'—'}</Value></Row>
      </Card></Group></>;break;
    case 'machine': content=<><Head title="This machine" sub="What Terum put on this laptop, and what it will ask you again for on the next one."/>
      <Group label="Identity"><Card><Row title={machine.name||'—'} desc={`${machine.os} · the name in the footer. Terum keeps no list of your machines and nothing here is committed.`}><Value quiet>This machine</Value></Row>{capabilities?.machineRegistry?<Row title="Other machines" desc="Nothing to list. Your installs are recorded in your people file and placed by sync on whichever machine runs it; tool approvals are asked again there."><Value quiet>—</Value></Row>:null}</Card></Group>
      <Group label="Placed here" note={<Note>The provenance ledger: the only paths Terum may ever touch. Tracked copies follow the team at sync; a pinned one stays until you install again.</Note>}><div className="placement-table" role="table" aria-label="Placed here"><div className="placement-head" role="row">{['Path','Scope','Version','Placed','State'].map(text=><span role="columnheader" key={text}>{text}</span>)}</div>{rows.PLACEMENTS.map(([path,skill,scope,version,placed,state],index)=><div role="row" className="placement-row" data-testid={'placement-row-'+index} key={path}><span role="cell" title={skill}>{path}</span><span role="cell">{scope}</span><span role="cell" className="board-mono" style={{color:version?'var(--tk-text1)':'var(--tk-text3)'}}>{version??'tracking'}</span><span role="cell">{status.ledger?relativeTime(placed):placed}</span><span role="cell">{state}</span></div>)}{rows.PLACEMENTS.length===0&&<Row title="Nothing placed on this machine yet."/>}<div className="placement-footer">{d.PLACEMENTS_N} placed · {status.counts.Global??'—'} global · {d.PINNED_N} pinned</div></div></Group>
      <Group label="Tool approvals on this machine" note={<Note>An approval covers exactly these tools. A changed or widened set asks again; there is no way to revoke one yet.</Note>}><Card>{rows.APPROVALS.map(([skill,grants,approved])=><Row key={skill} title={skill} desc={`Approved ${status.ledger?relativeTime(approved):approved}`}><div className="settings-chips" style={{maxWidth:320}}>{grants.map(grant=><Chip key={grant}>{grant}</Chip>)}</div></Row>)}{rows.APPROVALS.length===0?<Row title="No tool approvals recorded."/>:!status.ledger&&<Row title="Other skills" desc="Declare no tools and place without asking."><Value quiet>No approval needed</Value></Row>}</Card></Group>
      <Group label="Quarantine" trailing={d.QUARANTINE!==null&&<Button icon="trash" onClick={prune} state={search.get('dialog')==='prune'?'pressed':'default'}>Prune…</Button>} note={<TerminalHint command="npx -y terum-skills@latest sync --prune" prefix="Prune stands for"/>}><Card>{rows.QUARANTINE===null?<Row title="Quarantine contents are not reported by this terum-skills version."/>:rows.QUARANTINE.length===0?<Row title="Quarantine is empty."/>:rows.QUARANTINE.map(([when,name,why,size])=><Row key={when+name} title={name} desc={`${why} · ${when}`}><Value quiet>{size}</Value></Row>)}</Card></Group>{features?.libraryProjects&&surfaces?.libraryProjects===true?<Group label="Projects" note={<Note>The folders this machine reads local skills from. Adding a folder is not sharing: it publishes nothing and approves no tool grant. Remove forgets the path only; nothing on disk changes. Nothing is added for you — this list changes only when you add or remove a project.</Note>}><Card>{status.roots.filter(r=>r.kind==='checkout').map(root=><Row key={root.id} title={root.label} desc={`${root.root} · ${root.rootState??'—'} · ${root.count??'—'} skill folders`}><Button kind="danger" disabled={action.busy} onClick={()=>void action.run(()=>backend.projects.remove(root.id))}>Remove</Button></Row>)}<Row title="Add a project…" desc="The folder's canonical path; a git checkout or a plain folder that holds .claude/skills."><WorkflowField aria-label="Project path" style={{width:320}} value={projectPath} disabled={action.busy} onChange={e=>setProjectPath(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add();}}/><Button disabled={action.busy||!projectPath.trim()} onClick={add}>Add</Button></Row></Card></Group>:null}</>;break;
    // S7l ships the real hook toggle; until the CLI reports hook state, this row is read-only and never
    // claims installed/not-installed — a pref-backed switch here changed nothing in ~/.claude/settings.json.
    case 'sync': content=<><Head title="Sync" sub="How this machine follows the team, and what it will never do without you."/>
      <Group label="Session-start hook"><Card><Row title="Sync at session start" desc={<>The hook runs <Mono>npx -y terum-skills@latest sync --hook</Mono> in the background, at most once an hour per team. Setup adds the entry to ~/.claude/settings.json with your consent, and leaving your last team removes it; the app cannot read or change that entry yet.</>}><Value quiet>Managed by setup</Value></Row><Row title="What it places without asking" desc="Updates whose tool grants have not changed, and skills that grant no tools. A new or widened grant waits in your Inbox until you approve it."/><Row title="Local edits to a placed copy" desc="Overwritten at sync and moved to quarantine, so nothing is lost and nothing stays stale."/></Card></Group>
      <Group label="On demand" note={<TerminalHint command="npx -y terum-skills@latest sync" prefix="Sync now fetches"/>}><Card><Row title="Sync now" desc={`Last fetched ${syncTime(team?.last_sync??null,!!status.ledger)} · ${team?.name??'—'}. Fetching updates team clones but never places, uploads, or edits local skills.`}><Button icon="refresh" onClick={sync} disabled={action.busy}>Sync now</Button></Row>{status.teams.filter(team=>team.pending.length>0).map(team=><Row key={team.key} title={team.name} desc="Work left undone; rerun the matching install or uninstall"/>)}{d.syncNote&&<Row title="Fetch timestamps" desc={d.syncNote}/>}<Row title="Quarantine" desc={d.QUARANTINE===null?'Quarantine contents are not reported by this terum-skills version.':`${d.QUARANTINE.length} folders${d.STORAGE.quarantine==='—'?'':` · ${d.STORAGE.quarantine}`}. Only prune deletes here, after listing every path.`}>{d.QUARANTINE!==null&&<Button icon="trash" onClick={prune}>Prune…</Button>}</Row></Card></Group></>;break;
    case 'updates': content=<><Head title="Updates" sub="Skills follow the team unless pinned; the CLI tells you about a release and never installs it for you."/>
      <Group label="Skills"><Card><Row title="Tracked installs" desc={`Re-placed at sync when the team copy changes. ${plural(trackedN,'placement')} on this machine.`}><Value quiet>Follow the team</Value></Row><Row title="Pinned installs" desc={`Installed at a version; they never move until you install again. ${d.PINNED_N} on this machine.`}><Value quiet>Stay put</Value></Row><Row title="Update notices" desc="An update lands in Inbox ▸ Updates when a tracked skill changed and could not be placed silently.">{toggle('updates:notices','Update notices')}</Row></Card></Group>
      <Group label="The CLI" note={<TerminalHint command="npx -y terum-skills@latest update" prefix="Prints the command, never runs it"/>}><Card><Row title="terum-skills" desc={updateSummary}><Button onClick={()=>dialog('update')}>Show update command</Button></Row><Row title="Release notice" desc="One line after a command when a newer release is advertised or observed, at most once a day per release. Silenced by the CI, NO_UPDATE_NOTIFIER or TERUM_SKILLS_NO_UPDATE_NOTIFIER environment variables, not from here."><Value quiet>On</Value></Row><Row title="Release probe" desc="Reads release tags from github.com/ryanliu-terum/terum-skills on an interactive sync, at most once a day, and whenever you run update — never from the session hook or a prune, and only while a team on this machine lives on GitHub. It runs no package manager and makes no registry request; a copy launched with npx also reads that cache's @latest entry, which can be the newer of the two."><Value quiet>GitHub tags</Value></Row></Card></Group>
      <Group label="The app" note={appUpdateMode==='none'?undefined:<Note>The CLI never installs a CLI release for you. The app is the one exception: it downloads its own new version here, and installs it when you quit, overnight, or when you press Install now — whichever you chose above.</Note>}><Card>{appUpdateMode==='none'?<Row title="Terum Skills app" desc={`${appVersion??'—'} · no update channel yet.`}><Value quiet>—</Value></Row>:<AppUpdateRows mode={appUpdateMode} appVersion={appVersion} report={report}/>}</Card></Group></>;break;
    case 'inbox': content=<><Head title="Inbox" sub="Which kinds of news reach you, and how the sidebar shows them."/><Group label="Kinds"><Card>{Object.entries(d.INBOX_KIND_TEXT).filter(([key])=>Object.hasOwn(inboxLabels,key)&&(capabilities?.offtargetKind||(key!=='alert'&&key!=='offtarget'))).map(([key,desc])=><Row key={key} title={inboxLabels[key]??key} desc={desc}><span className="settings-toggle-hit"><Switch role="checkbox" aria-label={inboxLabels[key]??key} checked={backend.prefs.get('inbox:kind:'+key,true)} onCheckedChange={value=>action.pref('inbox:kind:'+key,value)}/></span></Row>)}</Card></Group>
      <Group label="Sidebar and bell"><Card><Row title="Sidebar rows" desc="How the sidebar groups the list under Inbox.">{choice('inbox:sidebar','Sidebar rows','Pushes · Updates · Alerts',['Pushes · Updates · Alerts'])}</Row><Row title="Badge on the bell" desc="Unread count in the top bar.">{toggle('inbox:badge','Badge on the bell')}</Row></Card></Group>
      <Group label="People" note={<Note>Follows are kept by this app on this machine. The team repo has no place for them yet, so another machine starts from nothing.</Note>}><Card><Row title="Following" desc="Follow someone from their card in the Marketplace; their new skills then land here."><Value quiet={!d.FOLLOWING.length}>{d.FOLLOWING.length?d.FOLLOWING.join(', '):'Nobody yet'}</Value></Row></Card></Group></>;break;
    case 'evals': {const k=d.K===null?'—':String(d.K);content=<><Head title="Evals" sub="The defaults a run starts from, and what an eval needs on this machine."/>
      <Group label="Defaults" note={<Note>{d.K===null?'The app passes no eval flags; terum-skills uses its own defaults.':<>These are the flags the app passes to <Mono>npx -y terum-skills@latest eval &lt;skill&gt; --k {d.K} --model sonnet</Mono>. The CLI keeps no defaults of its own.</>}</Note>}><Card><Row title="Repetitions per case" desc={d.K===null?'terum-skills keeps no default k; the CLI decides per run.':`k = ${k} gates on the verdict band alone; k = 10 for a receipt whose sign test means something.`}>{d.K!==null&&choice('eval:k','Repetitions per case',k,['1','3','5','10'])}</Row><Row title="Model for the arms" desc="Every number on one surface comes from one model; the Library names it beside the counts.">{choice('eval:model','Model for the arms','sonnet',['sonnet'])}</Row><Row title="Judge" desc="Asked twice, in both orderings; a disagreement is a tie.">{choice('eval:judge','Judge','sonnet',['sonnet'])}</Row><Row title="Escalation judge" desc="For a split judge. Named in the spec; the CLI does not take it yet."><Value quiet>opus · not yet</Value></Row></Card></Group>
      <Group label="On this machine"><Card><Row title="Run queued evals overnight" desc="between 01:00 and 05:00, while the app is open and idle">{toggle('evals:overnight','Run queued evals overnight')}</Row><Row title="Agent CLI" desc="Evals drive the claude CLI on this machine, on your own subscription. No cap on spend exists; the estimate before a run is the only guard."><StatusValue kind={d.AGENT_CLI==='—'?'unknown':'ok'}>{d.AGENT_CLI}{d.AGENT_CLI_AUTH === 'signed-in' ? ' · signed in' : ''}</StatusValue></Row><Row title="Sandbox" desc="Each arm runs with project-scoped settings only, so your global skills cannot leak into a result."><Value mono>--setting-sources project</Value></Row><Row title="Run trees" desc={`evals/${team?.key??'—'} · ${d.STORAGE.evals_n??'—'} runs · ${d.STORAGE.evals}, transcripts included. Nothing prunes these.`}>{team&&finder(`~/.terum/skills/evals/${team.key}`)}</Row><Row title="Commit receipts" desc="A finished run is committed to the team repo as one immutable file, after secret redaction.">{toggle('eval:commit','Commit receipts')}</Row></Card></Group></>;break;}
    case 'publishing': content=<><Head title="Publishing" sub="Publishing deliberately mints a version from a local skill folder."/>
      <Group label="Publish"><Card><Row title="Local skills" desc="Choose a local skill in the Library and publish it when you are ready. Sync only fetches team clones."/><Row title="Versions" desc="Published versions are immutable; later edits remain on this machine until you publish again."/></Card></Group></>;break;
    case 'appearance': content=<><Head title="Appearance" sub="This app&#39;s own preferences. They live with the app, not in the team or in ~/.terum."/><Group label="Look"><Card><Row title="Theme" desc="Follow the system, or a fixed theme."><div className="settings-theme" role="group" aria-label="Theme">{d.THEME_OPTIONS.map(label=><button key={label} type="button" aria-pressed={theme===label.toLowerCase()} onClick={()=>{const value=label.toLowerCase();if(value==='dark'||value==='light'||value==='system'){setTheme(value as Theme);if(search.has('theme'))setSearch(p=>{p.set('theme',value);return p;});}}}>{label}</button>)}</div></Row><Row title="Open at start">{choice('appearance:start','Open at start','Library ▸ Global',['Library ▸ Global'])}</Row><Row title="Sidebar counts" desc="Skill counts beside each list and unread counts under Inbox.">{toggle('appearance:counts','Sidebar counts')}</Row><Row title="Machine name in the footer">{toggle('appearance:machine','Machine name in the footer')}</Row></Card></Group><Group label="Keyboard"><Card>{rows.SHORTCUTS.map(([label,key])=><Row key={label} title={label}><Kbd>{key}</Kbd></Row>)}</Card></Group></>;break;
    case 'advanced': content=<><Head title="Advanced" sub="Where things live on this machine, diagnostics, and the two things that cannot be undone from here."/>
      <Group label="Local state"><Card><Row title="Local state" desc="~/.terum/skills · config, team clones, cache, quarantine, run stamps, eval runs. Nothing in it is team truth. The clones, cache and run stamps are disposable — setup and team join rebuild them. config.json is not: delete it and every skill Terum placed goes invisible to the tool (no ledger entry, so sync neither refreshes nor adopts those folders and install refuses their targets until you re-install each one with --force), every tool approval is asked again, and your handle, email and display name are re-asked.">{finder('~/.terum/skills')}</Row><Row title="Pinned checkouts" desc={`cache/${team?.key??'—'} · ${d.STORAGE.cache_n??'—'} versions`}><Value quiet>{d.STORAGE.cache}</Value></Row><Row title="Eval runs" desc={`evals/${team?.key??'—'} · ${d.STORAGE.evals_n??'—'} runs, transcripts included. Nothing prunes these.`}><Value quiet>{d.STORAGE.evals}</Value></Row></Card></Group>
      <Group label="Diagnostics" note={<TerminalHint command="npx -y terum-skills@latest status" prefix="Run stands for"/>}><Card><Row title="Status" desc="Prints the team's clone state, roster and counts, and how stale the last sync is."><Button icon="terminal" onClick={()=>dialog('status')}>Run</Button></Row><Row title="Logs" desc="The CLI prints as it goes and keeps no log file. Copy a command's output from the terminal."><Value quiet>—</Value></Row></Card></Group>
      <Group label="Danger zone" note={<TerminalHint command="npx -y terum-skills@latest uninstall" prefix="Remove stands for"/>}><Card><Row title="Session-start hook" desc="Removed with your last team, or by the removal below; there is no separate switch."/><Row title="Remove terum-skills from this machine" desc="Your team on this machine: placed skills, clones, cache, the session hook. A record is written to backups/ first. Your people files in the team repos are untouched."><Button kind="danger" state={search.get('dialog')==='remove'?'pressed':'default'} disabled={removal.current!==null} onClick={()=>dialog('remove')}>Remove…</Button></Row></Card></Group></>;break;
    // The latest CLI release comes from the update check the Updates section runs (report.latest); a backend that
    // serves a real CLI_LATEST (the mock) keeps it. When neither knows, the "available" clause is omitted — the
    // row never claims "— available".
    case 'about': {const latest=report?.latest??(d.CLI_LATEST!==null&&d.CLI_LATEST!=='—'?d.CLI_LATEST:null);content=<><Head title="About" sub=""/><Group label="Versions" note={<TerminalHint command="npx -y terum-skills@latest update" prefix="Check stands for"/>}><Card><Row title="Terum Skills app"><Value>{d.APP_VERSION}</Value></Row><Row title="terum-skills CLI" desc={latest?`${latest} available`:undefined}><Value>{d.CLI_VERSION}</Value><Button kind="ghost" icon="refresh" onClick={()=>navigate('/settings/updates?dialog=update'+(search.get('__mock')?'&__mock='+search.get('__mock'):''))}>Check</Button></Row><Row title="Agent CLI"><Value>{d.AGENT_CLI}</Value></Row><Row title="Platform"><Value>{machine.os}</Value></Row></Card></Group><Group label="Project"><Card><Row title="Feedback and requests"><a href={'https://'+d.COMMUNITY} onClick={e=>{e.preventDefault();void action.perform(()=>backend.openUrl('https://'+d.COMMUNITY));}}>{d.COMMUNITY}</a></Row><Row title="License" desc="The tool is Apache-2.0. The team's skills stay in the team's own repository."><Value>Apache-2.0</Value></Row></Card></Group></>;break;}
    default: content=<><Head title="Account" sub="Who you are to GitHub and to the team."/>
      <Group label="GitHub"><Card><Row title="GitHub" desc="Tool presence only; authentication is not checked. Creating a team or inviting needs gh; joining and syncing use the git credentials this machine already has.">{status.tools.git&&status.tools.gh?<StatusValue>git present · gh present</StatusValue>:<Value quiet>{`${status.tools.git?'git present':'git absent'} · ${status.tools.gh?'gh present':'gh absent'}`}</Value>}<Button kind="ghost" icon="external-link" onClick={()=>setSignIn(true)}>Open gh</Button></Row><Row title="Access to team repos" desc="gh signs the API calls; git pulls and pushes with your existing credentials. Terum stores no token of its own, and a token an older version stored is ignored."><Value quiet>Ambient git credentials</Value></Row></Card></Group>
      <Group label="Identity" note={<Note>These form the author line on every skill you share: <Mono>{me.name} &lt;{me.email}&gt;</Mono>. Changing them rewrites that line at the next sync.</Note>}><Card><Row title="Name">{field('name','Name',d.ME.name)}</Row><Row title="Email">{field('email','Email',d.ME.email)}</Row><Row title="Default handle" desc="Suggested whenever you join a team.">{field('defaultHandle','Default handle',d.ME.default_handle)}</Row><Row title={`Handle on ${team?.name??'—'}`} desc="Fixed once your people file exists."><LockedValue>{me.handle}</LockedValue></Row></Card></Group>
      <Group label="Session" note={<TerminalHint command="gh auth logout" prefix="From the terminal"/>}><Card><Row title="Sign out" desc="Signs gh out on this machine. Terum has no account of its own, so nothing else changes."><Button onClick={()=>setSignOut(true)}>Sign out</Button></Row></Card></Group></>;
  }
  return <>{content}{section==='advanced'&&removal.notice?<div role="status">{removal.notice}</div>:null}{syncAction.popup}{identityNotice?<Dialog open onOpenChange={open=>{if(!open)setIdentityNotice(null);}}><WorkflowPopup><DialogTitle>Identity saved</DialogTitle><div role="status">{identityNotice}</div><Button onClick={()=>setIdentityNotice(null)}>Close</Button></WorkflowPopup></Dialog>:null}{section==='updates'&&search.get('dialog')!=='update'&&updateError&&<div role="alert" className="settings-action-error">{updateError}</div>}{section==='updates'&&search.get('dialog')==='update'&&<Dialog open onOpenChange={open=>{if(!open)closeUpdate();}}><DialogPopup><DialogTitle>Update command</DialogTitle>{report?<>{report.description!==updateSummary&&<p>{report.description}</p>}<pre className="board-mono" style={{whiteSpace:'pre-wrap'}}>{report.advice.join('\n')}</pre></>:<p role={updateError?'alert':'status'}>{updateError??'Loading update advice…'}</p>}<Button onClick={closeUpdate}>Close</Button></DialogPopup></Dialog>}{signOut?<WorkflowDialog title="Sign out from a terminal" body="Run gh auth logout in a terminal. Terum has no account of its own, so nothing else changes." primary="Copy command" command="gh auth logout" close={()=>setSignOut(false)} submit={()=>void action.perform(()=>backend.copyToClipboard('gh auth logout'))} busy={action.busy} error={action.error}/>:null}{signIn?<WorkflowDialog title="Sign in from a terminal" body="Run gh auth login in a terminal, then return here and try again. This app does not change your credentials." primary="Copy command" command="gh auth login" close={()=>setSignIn(false)} submit={()=>void action.perform(()=>backend.copyToClipboard('gh auth login'))} busy={action.busy} error={action.error}/>:null}{action.error&&<div role="alert" className="settings-action-error"><RichText text={action.error}/></div>}<SettingsDialogs section={section} data={d} status={status}/></>;
}

function syncTime(value:string|null,live=false):string {
 if(value===null)return 'No sync recorded on this machine';
 if(!/^\d{4}-\d{2}-\d{2}T/.test(value))return live?'—':value;
 return relativeTime(value);
}
