import { afterEach,beforeEach,expect,it,vi } from 'vitest';
import { cleanup,fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { readFileSync } from 'node:fs';
import { App } from '../../app/App';
import { Providers } from '../../app/providers';
import { useUiStore } from '../../app/store';
import { BackendContext } from '../../backend';
import { createMockBackend } from '../../backend/mock';
import { createRun } from '../../backend/mock/run';
import { design } from '../../backend/mock/data';
import { decodeText } from '../../lib/fixture-text';
import { useOnboardingStore } from './onboarding-store';
const backend=createMockBackend();
function open(route:string){location.hash=route;return render(<Providers><BackendContext value={backend}><App/></BackendContext></Providers>);}
beforeEach(()=>{localStorage.clear();useUiStore.setState({theme:'dark',overviewHidden:false});useUiStore.getState().setTheme('dark');useOnboardingStore.getState().setSkipped([]);});
afterEach(()=>{cleanup();location.hash='';vi.restoreAllMocks();});
it.each([['boot','Setting up Terum'],['welcome',decodeText(design.WELCOME_LINES[0]??'')],['style','Choose your style'],['basics','The basics'],['team','Your workspace'],['feedback','Feedback and requests'],['done','Good to go!']])('renders the %s step title and a main landmark',async(step,title)=>{open('#/onboarding/'+step);expect(await screen.findByRole('heading',{name:title})).toBeInTheDocument();expect(screen.getByRole('main')).toBeInTheDocument();await waitFor(()=>expect(document.documentElement.dataset.appReady).toBe('true'));});
it.each([['manage','Manage','deploy-check'],['eval','Eval','Quality'],['share','Share','Share with CLI'],['search','Search','Ryan Liu'],['more','More to come','Install from Slack with one click']])('renders the %s Basics panel and all tab labels',async(tab,label,content)=>{open('#/onboarding/basics?tab='+tab);const panel=await screen.findByRole('tabpanel');expect(panel).toHaveTextContent(content);expect(screen.getAllByRole('tab')).toHaveLength(5);expect(screen.getByRole('tab',{name:label})).toHaveAttribute('aria-selected','true');});
it('renders the decoded boot failure and one of four status steps',async()=>{open('#/onboarding/boot?__mock=error');expect(await screen.findByRole('alert')).toHaveTextContent(decodeText(design.ONBOARD_FETCH_ERROR));expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuenow','1');expect(screen.queryByLabelText('Onboarding progress')).toBeNull();});
it('marks the Light card from pick without requiring a theme override',async()=>{open('#/onboarding/style?pick=light');expect(await screen.findByRole('radio',{name:'Light'})).toHaveAttribute('aria-checked','true');expect(screen.getByRole('radio',{name:'System'})).toHaveAttribute('aria-checked','false');});
it('selects System by default and applies a picked theme to the URL and store',async()=>{open('#/onboarding/style');expect(await screen.findByRole('radio',{name:'System'})).toHaveAttribute('aria-checked','true');fireEvent.click(screen.getByRole('radio',{name:'Light'}));await waitFor(()=>expect(document.documentElement.dataset.theme).toBe('light'));expect(location.hash).toContain('pick=light');expect(useUiStore.getState().theme).toBe('light');});
it('keeps the Light board compatible with the protected route lacking pick',async()=>{open('#/onboarding/style?theme=light');expect(await screen.findByRole('radio',{name:'Light'})).toHaveAttribute('aria-checked','true');expect(document.documentElement.dataset.theme).toBe('light');});
it('marks a skipped Basics step in the store and step map',async()=>{open('#/onboarding/basics');fireEvent.click(await screen.findByRole('button',{name:'Skip the tour'}));await screen.findByRole('heading',{name:'Your workspace'});expect(useOnboardingStore.getState().onboardingSkipped).toEqual(['Basics']);expect(backend.prefs.get('onboardingSkipped',[])).toEqual(['Basics']);expect(within(screen.getByLabelText('Onboarding progress')).getByLabelText('Basics')).toHaveAttribute('data-skipped','true');});
it('retains skipped steps when reopening the flow',async()=>{backend.prefs.set('onboardingSkipped',['Basics','invalid',17]);open('#/onboarding/feedback');await screen.findByRole('heading',{name:'Feedback and requests'});await waitFor(()=>expect(useOnboardingStore.getState().onboardingSkipped).toEqual(['Basics']));expect(within(screen.getByLabelText('Onboarding progress')).getByLabelText('Basics')).toHaveAttribute('data-skipped','true');});
it('does not advance Skip when saving the preference fails',async()=>{open('#/onboarding/team');await screen.findByRole('heading',{name:'Your workspace'});vi.spyOn(backend.prefs,'set').mockImplementation(()=>{throw new Error('Storage unavailable.');});fireEvent.click(screen.getByRole('button',{name:'Skip for now'}));expect(await screen.findByRole('alert')).toHaveTextContent('Storage unavailable.');expect(location.hash).toBe('#/onboarding/team');expect(useOnboardingStore.getState().onboardingSkipped).toEqual([]);});
it('renders the live Library underneath Done with all skills and counts',async()=>{open('#/onboarding/done');await screen.findByRole('heading',{name:'Good to go!'});expect(await screen.findByText('15 of 30 skills')).toBeInTheDocument();expect(screen.getAllByTestId(/^skill-card-/)).toHaveLength(15);fireEvent.click(screen.getByRole('button',{name:'Open the Library'}));await waitFor(()=>expect(location.hash).toBe('#/library/global'));expect(screen.queryByRole('dialog')).toBeNull();});
it('navigates forward across Basics tabs and back without losing the theme',async()=>{open('#/onboarding/basics?theme=light');fireEvent.click(await screen.findByRole('button',{name:'Next'}));expect(await screen.findByRole('tab',{name:'Eval'})).toHaveAttribute('aria-selected','true');fireEvent.click(screen.getByRole('button',{name:'Back'}));expect(screen.getByRole('tab',{name:'Manage'})).toHaveAttribute('aria-selected','true');expect(location.hash).toContain('theme=light');});
it('advances Welcome on Enter and returns with Back',async()=>{open('#/onboarding/welcome');await screen.findByRole('heading',{name:decodeText(design.WELCOME_LINES[0]??'')});fireEvent.keyDown(document.body,{key:'Enter'});await screen.findByRole('heading',{name:'Choose your style'});fireEvent.click(screen.getByRole('button',{name:'Back'}));expect(await screen.findByRole('heading',{name:decodeText(design.WELCOME_LINES[0]??'')})).toBeInTheDocument();});
it('invites the workspace logins and advances on success',async()=>{const invite=vi.spyOn(backend,'invite');open('#/onboarding/team');fireEvent.click(await screen.findByRole('button',{name:'Invite'}));await screen.findByRole('heading',{name:'Feedback and requests'});expect(invite).toHaveBeenCalledWith({logins:['sortiz']});});
it('rejects an empty workspace name before inviting',async()=>{const invite=vi.spyOn(backend,'invite');open('#/onboarding/team');fireEvent.change(await screen.findByRole('textbox',{name:'Workspace name'}),{target:{value:' '}});fireEvent.click(screen.getByRole('button',{name:'Invite'}));expect(await screen.findByRole('alert')).toHaveTextContent('Enter a workspace name.');expect(invite).not.toHaveBeenCalled();});
it('keeps a failed workspace invite on its step',async()=>{vi.spyOn(backend,'invite').mockImplementation(()=>createRun(async()=>({ok:false,error:'Invite failed.'})));open('#/onboarding/team');fireEvent.click(await screen.findByRole('button',{name:'Invite'}));expect(await screen.findByRole('alert')).toHaveTextContent('Invite failed.');expect(location.hash).toBe('#/onboarding/team');});
it('opens the exact community invitation through the backend',async()=>{const editor=vi.spyOn(backend,'openInEditor');open('#/onboarding/feedback');fireEvent.click(await screen.findByRole('button',{name:'Join'}));await screen.findByRole('heading',{name:'Good to go!'});expect(editor).toHaveBeenCalledWith(design.ONBOARD_COMMUNITY.invite);});
it('continues offline from a boot error',async()=>{open('#/onboarding/boot?__mock=error');fireEvent.click(await screen.findByRole('button',{name:'Continue offline'}));expect(await screen.findByText('15 of 30 skills')).toBeInTheDocument();expect(location.hash).toBe('#/library/global');});
it('uses Manage for an unknown Basics tab and System for an unknown pick',async()=>{open('#/onboarding/basics?tab=unknown');expect(await screen.findByRole('tab',{name:'Manage'})).toHaveAttribute('aria-selected','true');cleanup();open('#/onboarding/style?pick=unknown');expect(await screen.findByRole('radio',{name:'System'})).toHaveAttribute('aria-checked','true');});
it('keeps miniature tokens equal to both generated palettes',()=>{const css=readFileSync('src/screens/onboarding/onboarding.css','utf8');for(const theme of ['dark','light'] as const){const block=css.match(new RegExp('\\[data-mini-theme='+theme+'\\]\\{([^}]+)\\}'))?.[1];expect(block).toBeDefined();for(const key of ['chrome','panel','bg2','border1','border2'] as const)expect(block).toContain('--mini-'+key+':'+design.TOKENS[key][theme==='dark'?0:1]);}});


it('shows sync status after join, with only three of four steps completed (D11)',async()=>{
 open('#/onboarding/boot');await screen.findByRole('heading',{name:'Setting up Terum'});
 expect(screen.getByText('Nothing new to place')).toBeInTheDocument();
 expect(screen.getByText('the join placed the Global set')).toBeInTheDocument();
 expect(screen.getByText('Approve updated tools for <skill>? · asked only when a grant changed upstream')).toBeInTheDocument();
 expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuenow','3');
 expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuemax','4');
});
it.each([['manage','npx -y terum-skills@latest install <ref>'],['share','npx -y terum-skills@latest connect']])('renders the fixture command for %s (CP-06)',async(tab,command)=>{
 const view=open('#/onboarding/basics?tab='+tab);await screen.findByRole('tabpanel');
 expect(view.container.querySelector('.onboarding-hint-slot')).toHaveTextContent(command);
});
