import { useState } from 'react';
import type { PropsWithChildren } from 'react';
import { useSearchParams } from 'react-router';
import type { Catalog } from '../../backend/types';
import { Button } from '../../components/ui/Button';
import { Icon } from '../../components/ui/Icon';
import { Switch } from '../../components/ui/Switch';
function Group({ label, children }: PropsWithChildren<{ label: string }>) { return <div className="market-filter-group"><span>{label}</span>{children}</div>; }
function Slider({ label, value, max, format }: { label: string; value: number; max: number; format: (n: number) => string }) { const [current, setCurrent] = useState(value); return <div className="market-slider"><div><span>{label}</span><span>{format(current)}</span></div><input aria-label={label} type="range" min={0} max={max} step={1} value={current} onChange={e => setCurrent(Number(e.target.value))} style={{ background: `linear-gradient(to right,var(--tk-brand) ${Math.min(1, current / max) * 100}%,var(--tk-bg4) ${Math.min(1, current / max) * 100}%)` }}/></div>; }
function Chips({ labels }: { labels: string[] }) { const [selected, setSelected] = useState<string[]>([]); return <div className="market-filter-chips">{labels.map(label => <button type="button" key={label} aria-pressed={selected.includes(label)} onClick={() => setSelected(old => old.includes(label) ? old.filter(x => x !== label) : [...old, label])}>{selected.includes(label) && <Icon name="check" size={12} stroke="2.5"/>}{label}</button>)}</div>; }
export function Filters({ catalog, onClose }: { catalog: Catalog; onClose: () => void }) {
  const [params, setParams] = useSearchParams(), [verdicts, setVerdicts] = useState(catalog.filterDefault.verdicts), [updated, setUpdated] = useState('Any time'), [hide, setHide] = useState(false), [reset, setReset] = useState(0);
  function clear() { setVerdicts([]); setUpdated('Any time'); setHide(false); setReset(n => n + 1); const next = new URLSearchParams(params); next.set('active', '0'); setParams(next); }
  return <div className="market-filters" role="region" aria-label="Marketplace filters" onKeyDown={e => { if (e.key === 'Escape') { e.stopPropagation(); onClose(); } }}><div className="market-filters-head"><span>Filters</span><Button kind="ghost" onClick={clear}>Clear</Button></div><div className="market-filters-columns"><div><Group label="Verdict"><div className="market-verdicts">{Object.entries(catalog.verdictCounts).map(([name, count]) => <label key={name} data-testid={'verdict-count-' + name}><span><input type="checkbox" checked={verdicts.includes(name)} onChange={e => setVerdicts(old => e.target.checked ? [...old, name] : old.filter(v => v !== name))}/><span className="market-checkbox">{verdicts.includes(name) && <Icon name="check" size={12} stroke="3"/>}</span><span>{name}</span></span><span>{count}</span></label>)}</div></Group><Slider key={'lift' + reset} label="Net lift · at least" value={reset ? 0 : catalog.filterDefault.lift_min} max={100} format={n => `+${n}%`}/><Slider key={'tokens' + reset} label="Context · at most" value={reset ? 10 : catalog.filterDefault.tokens_max} max={10} format={n => `${n}k tokens`}/><Slider key={'installs' + reset} label="Installed by · at least" value={reset ? 0 : catalog.filterDefault.installs_min} max={catalog.teamN} format={n => `${n} teammates`}/></div><div><Group label="Updated"><div className="market-segmented">{['7 days', '30 days', 'Any time'].map(value => <button type="button" key={value} aria-pressed={value === updated} onClick={() => setUpdated(value)}>{value}</button>)}</div></Group><Group label="List"><Chips key={'lists' + reset} labels={['Global', ...catalog.projects.map(p => p.name)]}/></Group><Group label="Category"><Chips key={'categories' + reset} labels={catalog.categories.map(c => c[0])}/></Group><Group label="Author"><div className="market-select"><select aria-label="Author" defaultValue=""><option value="">Anyone</option>{catalog.people.map(p => <option key={p.handle} value={p.handle}>{p.name}</option>)}</select><Icon name="chevron-down" size={14} stroke="2"/></div></Group></div></div><div className="market-filters-foot"><label><Switch checked={hide} onCheckedChange={setHide} aria-label="Hide skills I have installed"/><span>Hide skills I have installed</span></label><Button kind="primary" onClick={onClose}>Show {catalog.filterCount} skills</Button></div></div>;
}
