import { Fragment, useState } from 'react';
import type { PropsWithChildren } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router';
import { useBackend, useFeatures, githubUrl } from '../../backend';
import type { Catalog, Person, Project, SkillCard as Card } from '../../backend/types';
import { Avatar, IconButton, SectionLabel, ShareBlock, Small } from '../../components/domain/Primitives';
import { SkillCard } from '../../components/domain/SkillCard';
import { token } from '../../components/domain/presentation';
import { Icon } from '../../components/ui/Icon';
import { ICON_PATHS } from '../../components/ui/icon-paths';
import type { IconName } from '../../components/ui/icon-paths';
import { Button } from '../../components/ui/Button';
import { Chip } from '../../components/ui/Chip';
import { activeFacets, personStatus, plural, pluralWord } from './market-data';
import { Filters } from './market-filters';
const CATEGORY_ICONS: Record<string, IconName> = {infra:'box',docs:'book-open',review:'eye',ops:'terminal',testing:'flask',data:'database',git:'git-commit',onboarding:'users',research:'search',security:'shield'};
function iconName(name: string): IconName { return CATEGORY_ICONS[name] ?? (Object.hasOwn(ICON_PATHS,name)?name as IconName:'tag'); }
export function CardRow({ names, catalog, cols = 3 }: { names: string[]; catalog: Catalog; cols?: number }) { const available = [...catalog.skills, ...catalog.extras]; return <div className="market-grid" data-columns={cols} style={{ gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))` }}>{names.map(name => { const skill = available.find(s => s.name === name); if (!skill) throw new Error(`Catalog is missing skill ${name}.`); return <MarketplaceSkillCard key={name} skill={skill}/>; })}</div>; }

function MarketplaceSkillCard({ skill }: { skill: Card }) {
  const navigate = useNavigate();
  // The shared card has no install-hint slot. Keep its layout and reserve that button's space,
  // then supply the board's icon + label in this family wrapper (footer top = 13 + 50 + 8 + 32 + 8).
  return <div className="market-card-wrap"><SkillCard skill={skill}/>{skill.installed !== 'placed' && <button className="market-card-install" type="button" title={skill.installed === 'recorded' ? 'Installed · not on this machine' : undefined} onClick={() => navigate('/skill/' + encodeURIComponent(skill.name) + '?dialog=install&root=marketplace')}><Icon name="arrow-down-to-line" size={14} stroke="1.75"/><span>{skill.installed === 'recorded' ? 'Reinstall' : 'Install'}</span></button>}</div>;
}
export function Mark({ name, small = false }: { name: string; small?: boolean }) { return <span className={'market-mark' + (small ? ' small' : '')}><Icon name={iconName(name)} size={small ? 15 : 16}/></span>; }
function FollowControl({ person, compact = false }: { person: Person; compact?: boolean }) {
  const backend = useBackend(), [following, setFollowing] = useState(() => backend.prefs.get('following:' + person.handle, false)), [error, setError] = useState<string | null>(null);
  function toggle() { try { backend.prefs.set('following:' + person.handle, !following); setFollowing(!following); setError(null); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save follow preference.'); } }
  return <span className="market-follow"><Button className={compact ? 'market-follow-compact' : ''} aria-label={`${following ? 'Unfollow' : 'Follow'} ${person.handle}`} aria-pressed={following} onClick={toggle} {...(!compact ? { icon: following ? 'check' as const : 'bell' as const } : {})}>{compact && <Icon name={following ? 'check-circle' : 'bell'} size={14} stroke="1.75" color={following ? token('good') : 'currentColor'}/>}<span>{following ? 'Following' : 'Follow'}</span></Button>{error && <span role="alert">{error}</span>}</span>;
}
export function Follow(props: {person:Person;compact?:boolean}){const features=useFeatures();return features?.follow?<FollowControl {...props}/>:null;}
function InstallMark({ installed }: { installed: boolean }) { return <span className="market-install-mark"><Icon name={installed ? 'check-circle' : 'arrow-down-to-line'} size={14} color={installed ? token('good') : 'currentColor'} stroke="1.75"/>{installed ? 'Installed' : 'Install'}</span>; }
export function ProjectCard({ project: q, expanded = false }: { project: Project; expanded?: boolean }) { const features=useFeatures();return <Link to={'/marketplace/projects/' + q.key} className={'market-project-card' + (expanded ? ' expanded' : '')} data-testid={'project-card-' + q.key}><div className="market-card-head"><Mark name={q.ico}/><span>{q.name}</span>{expanded && <InstallMark installed={q.installed}/>}</div>{q.desc && <span className="market-project-desc">{q.desc}</span>}<div className="market-card-chips"><div><Chip>{q.skills}{' ' + pluralWord(q.skills, 'skill')}</Chip>{features?.projectMembers?<Chip>{q.members} members</Chip>:null}{expanded && q.evaluated !== null && <Chip>{q.evaluated} of {q.skills} evaluated</Chip>}</div>{!expanded && <InstallMark installed={q.installed}/>}</div>{expanded && q.admin !== null && <div className="market-project-foot"><div><Avatar initials={q.admin.initials} size={20}/><span>{q.admin.name}</span><Small>{q.updated !== null ? 'admin · updated ' : 'admin'}{q.updated}</Small></div><Small><span className="board-mono">{q.remote}</span></Small></div>}</Link>; }
export function PersonCard({ person: q }: { person: Person }) { const features=useFeatures();const ident=[features?.memberRole?q.role:'',q.handle===q.name?'':q.handle].filter(Boolean).join(' · ');return <article className="market-person-card" data-testid={'person-card-' + q.handle}><div className="market-card-head"><div><Avatar initials={q.initials} size={32}/></div><div className="market-person-ident"><Link to={'/marketplace/people/' + q.handle}>{q.name}</Link>{ident?<span>{ident}</span>:null}</div><Follow person={q} compact/></div><div className="market-person-lines"><span>{q.publishLine}</span>{features?.memberRole?<span>{q.teamsLine}</span>:null}</div><div className="market-inline"><Chip>{plural(q.skills.length, 'skill')}</Chip><Chip>{plural(q.adoption, 'install')}</Chip>{features?.follow?<Chip>{q.followers===null?'—':plural(q.followers, 'follower')}</Chip>:null}</div></article>; }
export function CategoryTile({ category: [key, , n] }: { category: Catalog['categories'][number] }) { return <Link to={'/marketplace/categories/' + key} className="market-category-tile"><Mark name={key} small/><div><span>{key}</span><span>{plural(n, 'skill')}</span></div></Link>; }
export function CategoryRow({ category: [key, , n], catalog }: { category: Catalog['categories'][number]; catalog: Catalog }) { const remaining = catalog.categoryRemaining[key] ?? 0; return <Link to={'/marketplace/categories/' + key} className="market-category-row" data-testid={'category-row-' + key}><Mark name={key} small/><div><span>{key}</span><span>{plural(n, 'skill')}</span></div><span>{catalog.categorySkills[key]?.join(' · ')}{remaining > 0 ? ` · +${remaining} more` : ''}</span><Icon name="chevron-right" size={14} stroke="2"/></Link>; }
export function Section({ title, subtitle, path, children }: PropsWithChildren<{ title: string; subtitle: string; path: string }>) { const navigate = useNavigate(); return <section className="market-section" aria-label={title}><div className="market-section-head"><div><h2>{title}</h2><span>{subtitle}</span></div><Button icon="chevron-right" iconOnly aria-label={'View all ' + title} onClick={() => navigate('/marketplace/' + path)}/></div>{children}</section>; }


export function MarketSearch({ placeholder = 'Search skills, people and projects', hero = false, catalog }: { placeholder?: string; hero?: boolean; catalog?: Catalog }) {
  const [params, setParams] = useSearchParams(), q = params.get('q') ?? '', [draft, setDraft] = useState(q), [lastQ, setLastQ] = useState(q);
  if (lastQ !== q) { setLastQ(q); setDraft(q); }
  const open = params.get('filters') === 'open'; const rawActive = params.get('active'); const active = activeFacets(rawActive, open ? 4 : 0);
  function change(key: string, value?: string) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next); }
  return <div className={'market-search' + (hero ? ' hero' : '')}><Icon name="search" size={16} color={token('text3')}/><input aria-label={placeholder} placeholder={placeholder} value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') change('q', draft); }}/>{q && <IconButton icon="x" size={20} iconSize={14} label="Clear search field" onClick={() => change('q')}/>}<span className="market-filter-button"><IconButton icon="filter" label="Filter marketplace" pressed={open} onClick={() => change('filters', open ? undefined : 'open')}/>{active > 0 && <span>{active}</span>}</span>{open && catalog && <Filters catalog={catalog} onClose={() => change('filters')}/>}</div>;
}
export function Crumbs({ parts, railOpen, onToggle }: { parts: string[]; railOpen?: boolean; onToggle?: () => void }) { const navigate = useNavigate(); return <div className="market-crumbs" data-rail-open={railOpen}><div><IconButton icon="arrow-left" size={28} label="Back to marketplace" onClick={() => navigate('/marketplace')}/><div>{parts.map((part, i) => <Fragment key={i}>{i > 0 && <span className="market-crumb-separator">/</span>}<span className={i === parts.length - 1 ? 'current' : ''}>{part}</span></Fragment>)}</div></div>{onToggle && <IconButton icon="panel-right" size={28} label={railOpen ? 'Close details rail' : 'Open details rail'} onClick={onToggle}/>}</div>; }


export function MarketRail({ project, person, repository }: { project?: Project; person?: Person; repository:string|null }) {
  const backend=useBackend(),features=useFeatures(),[error,setError]=useState<string|null>(null);
  const url=githubUrl(project?.remote??repository??'');
  if (!project && !person) throw new Error('A marketplace rail needs a project or person.');
  const q = project, p = person;
  const status = q ? q.installed ? ['Installed', q.path ? `${plural(q.skills, 'skill')} placed in ${q.path}` : `${plural(q.skills, 'skill')} placed on this machine`] : ['Not installed', 'Placed by install project, inside a checkout of this repo'] : p ? personStatus(p) : [];
  const rows: [string, string, boolean?][] = q ? [['Skills', String(q.skills)], ['Members', String(q.members)], ...(q.evaluated !== null ? [['Evaluated', `${q.evaluated} of ${q.skills}`] as [string, string]] : []), ...(q.updated !== null ? [['Updated', q.updated] as [string, string]] : []), ['Remote', q.remote, true]] : p ? [['Skills', String(p.onDisk[1])], ['Installs', `${p.adoption} · from people files`], ['Followers', String(p.followers)], ['Joined', p.joined], ['Last publish', p.lastPublish]] : [];
  return <aside className="market-rail"><div className="market-status"><span>Status</span><span>{status[0]}</span><span>{status[1]}</span></div><div className="market-rail-details"><SectionLabel>Details</SectionLabel><div>{rows.filter(([label])=>(label!=='Followers'||features?.follow)&&(label!=='Members'||features?.projectMembers)).map(([label, value, mono]) => <div className="market-detail-row" key={label}><span>{label}</span><span className={mono ? 'board-mono' : ''}>{value}</span></div>)}</div></div><div className="market-repo"><SectionLabel>{q ? 'Repo' : 'People file'}</SectionLabel><div><a {...(url?{href:url,onClick:(event:React.MouseEvent<HTMLAnchorElement>)=>{event.preventDefault();void backend.openUrl(url).then(result=>{if(!result.ok)setError(result.error);},reason=>setError(String(reason)));}}:{})}>{repository?.replace(/^(?:https:\/\/)?github\.com\//,'')??'—'}</a>{error?<span role="alert">{error}</span>:null}<span>{q ? `team.json · projects.${q.key}` : `people/${p?.handle}.json`}</span></div></div>{q && q.admin !== null && <div className="market-admin"><SectionLabel>Admin</SectionLabel><div><Avatar initials={q.admin.initials} size={28}/><div><span>{q.admin.name}</span><Small>{features?.memberRole?`${q.admin.role} · `:''}{q.admin.handle}</Small></div></div></div>}<div className="market-rail-spacer"/><ShareBlock command={`npx -y terum-skills@latest install ${q ? 'project ' + q.key : 'member ' + p?.handle}`}/></aside>;
}
