import { useState } from 'react';
import type { PropsWithChildren } from 'react';
import { useSearchParams } from 'react-router';
import type { Catalog } from '../../backend/types';
import { Button } from '../../components/ui/Button';
import { Icon } from '../../components/ui/Icon';
import { Switch } from '../../components/ui/Switch';
import type { Facets } from './market-facets';
import { clearedFacets, defaultFacets, facetMatches, parseFacets, serializeFacets, stripFacets, TOKENS_CAP } from './market-facets';
function Group({ label, children }: PropsWithChildren<{ label: string }>) { return <div className="market-filter-group"><span>{label}</span>{children}</div>; }
function Slider({ label, value, max, format, onChange }: { label: string; value: number; max: number; format: (n: number) => string; onChange: (n: number) => void }) { return <div className="market-slider"><div><span>{label}</span><span>{format(value)}</span></div><input aria-label={label} type="range" min={0} max={max} step={1} value={value} onChange={e => onChange(Number(e.target.value))} style={{ background: `linear-gradient(to right,var(--tk-brand) ${Math.min(1, value / max) * 100}%,var(--tk-bg4) ${Math.min(1, value / max) * 100}%)` }}/></div>; }
function Chips({ labels, selected, onChange }: { labels: string[]; selected: string[]; onChange: (next: string[]) => void }) { return <div className="market-filter-chips">{labels.map(label => <button type="button" key={label} aria-pressed={selected.includes(label)} onClick={() => onChange(selected.includes(label) ? selected.filter(x => x !== label) : [...selected, label])}>{selected.includes(label) && <Icon name="check" size={12} stroke="2.5"/>}{label}</button>)}</div>; }
export function Filters({ catalog, onClose }: { catalog: Catalog; onClose: () => void }) {
  const [params, setParams] = useSearchParams();
  const [facets, setFacets] = useState<Facets>(() => parseFacets(params) ?? defaultFacets(catalog));
  const patch = (part: Partial<Facets>) => setFacets(old => ({ ...old, ...part }));
  // Live CTA count over the catalog; with the default selection this equals the build-time catalog.filterCount, so the drawn default board does not move.
  const matching = catalog.skills.filter(s => facetMatches(s, facets, catalog)).length;
  function clear() { setFacets(clearedFacets()); const next = stripFacets(params); next.set('active', '0'); setParams(next); }
  // Commit and close in ONE URL write: onClose() would issue a second setSearchParams from the caller's (stale) render-scope params and clobber the freshly committed facets, so the commit deletes filters=open itself.
  function commit() { const next = serializeFacets(facets, params); next.delete('filters'); setParams(next); }
  return <div className="market-filters" role="region" aria-label="Marketplace filters" onKeyDown={e => { if (e.key === 'Escape') { e.stopPropagation(); onClose(); } }}><div className="market-filters-head"><span>Filters</span><Button kind="ghost" onClick={clear}>Clear</Button></div><div className="market-filters-columns"><div><Group label="Verdict"><div className="market-verdicts">{Object.entries(catalog.verdictCounts).map(([name, count]) => <label key={name} data-testid={'verdict-count-' + name}><span><input type="checkbox" checked={facets.verdicts.includes(name)} onChange={e => patch({ verdicts: e.target.checked ? [...facets.verdicts, name] : facets.verdicts.filter(v => v !== name) })}/><span className="market-checkbox">{facets.verdicts.includes(name) && <Icon name="check" size={12} stroke="3"/>}</span><span>{name}</span></span><span>{count??'—'}</span></label>)}</div></Group><Slider label="Net lift · at least" value={facets.liftMin} max={100} format={n => `+${n}%`} onChange={n => patch({ liftMin: n })}/><Slider label="Context · at most" value={facets.tokensMax} max={TOKENS_CAP} format={n => `${n}k tokens`} onChange={n => patch({ tokensMax: n })}/><Slider label="Installed by · at least" value={facets.installsMin} max={catalog.teamN} format={n => `${n} teammates`} onChange={n => patch({ installsMin: n })}/></div><div><Group label="Updated"><div className="market-segmented">{['7 days', '30 days', 'Any time'].map(value => <button type="button" key={value} aria-pressed={value === facets.updated} onClick={() => patch({ updated: value })}>{value}</button>)}</div></Group><Group label="List"><Chips labels={['Global', ...catalog.projects.map(p => p.name)]} selected={facets.lists} onChange={lists => patch({ lists })}/></Group><Group label="Category"><Chips labels={catalog.categories.map(c => c[0])} selected={facets.categories} onChange={categories => patch({ categories })}/></Group><Group label="Author"><div className="market-select"><select aria-label="Author" value={facets.author} onChange={e => patch({ author: e.target.value })}><option value="">Anyone</option>{catalog.people.map(p => <option key={p.handle} value={p.handle}>{p.name}</option>)}</select><Icon name="chevron-down" size={14} stroke="2"/></div></Group></div></div><div className="market-filters-foot"><label><Switch checked={facets.hide} onCheckedChange={hide => patch({ hide })} aria-label="Hide skills I have installed"/><span>Hide skills I have installed</span></label><Button kind="primary" onClick={commit}>Show {matching} skills</Button></div></div>;
}
