import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { HOOK_ENTRY, hookInstalled, installHook, removeHook } from '../hook.js';
import { temporaryDirectory } from './fixtures.js';

/**
 * Blind adversarial cases for the §8 settings-file contract: generated by a model that saw only
 * the contract (scripts/codex-adversarial-tests.sh, 2026-09-05), adjudicated by hand, then pinned.
 * Case 8's "invalid JSON" expectation was adjudicated the other way: `hookInstalled` surfaces the
 * "Cannot edit" error at the earliest read rather than answering false, so the y/N is never asked
 * about a file that cannot be edited.
 */
async function target() {
  const root = await temporaryDirectory('terum-hook-adv-');
  const backupDir = join(root, 'backups');
  await mkdir(backupDir, { recursive: true });
  await writeFile(join(backupDir, '.keep'), '');
  return { root, settingsFile: join(root, 'settings.json'), backupDir };
}
const backups = async (dir: string) => (await readdir(dir)).filter((name) => /^settings\..+\.json$/.test(name));
const entry = (command: string, matcher?: string) => ({ ...(matcher ? { matcher } : {}), hooks: [{ type: 'command', command }] });

describe('session hook — adversarial (§8)', () => {
  it('1. replaces a hand-edited match in place between preserved neighbours and keeps every other event and key', async () => {
    const t = await target();
    const original = `${JSON.stringify({ before: 1, hooks: { SessionStart: [entry('echo alpha', 'alpha'), entry('npm exec terum-skills old', 'legacy'), entry('echo omega', 'omega')], PreToolUse: [{ x: true }] }, after: 2 }, null, 2)}\n`;
    await writeFile(t.settingsFile, original);
    await expect(installHook(t)).resolves.toBe('replaced');
    const after = JSON.parse(await readFile(t.settingsFile, 'utf8'));
    expect(after.hooks.SessionStart).toEqual([entry('echo alpha', 'alpha'), HOOK_ENTRY, entry('echo omega', 'omega')]);
    expect(after.hooks.PreToolUse).toEqual([{ x: true }]);
    expect(Object.keys(after)).toEqual(['before', 'hooks', 'after']);
    expect(await readFile(t.settingsFile, 'utf8')).toBe(`${JSON.stringify(after, null, 2)}\n`);
    const saved = await backups(t.backupDir);
    expect(saved).toHaveLength(1);
    expect(await readFile(join(t.backupDir, saved[0]!), 'utf8')).toBe(original);
  });

  it('2. collapses several pre-existing matches to one canonical entry at the first match, and does not back up twice', async () => {
    const t = await target();
    await writeFile(join(t.backupDir, 'settings.2026-01-01T00-00-00-000Z.json'), 'older backup');
    await writeFile(t.settingsFile, JSON.stringify({ hooks: { SessionStart: [{ matcher: 'one', hooks: [{ command: 'terum-skills first' }] }, { matcher: 'keep', hooks: [{ command: 'echo keep' }] }, { matcher: 'two', hooks: [{ command: 'echo terum-skills second' }] }] } }));
    await expect(installHook(t)).resolves.toBe('replaced');
    const after = JSON.parse(await readFile(t.settingsFile, 'utf8'));
    expect(after.hooks.SessionStart).toEqual([HOOK_ENTRY, { matcher: 'keep', hooks: [{ command: 'echo keep' }] }]);
    expect(await backups(t.backupDir)).toEqual(['settings.2026-01-01T00-00-00-000Z.json']);
  });

  it('3. creates an absent file with exactly the canonical document, mode 0600, and no backup', async () => {
    const t = await target();
    await expect(installHook(t)).resolves.toBe('installed');
    expect(await readFile(t.settingsFile, 'utf8')).toBe(`${JSON.stringify({ hooks: { SessionStart: [HOOK_ENTRY] } }, null, 2)}\n`);
    if (process.platform !== 'win32') expect((await stat(t.settingsFile)).mode & 0o777).toBe(0o600);
    expect(await backups(t.backupDir)).toEqual([]);
  });

  it('4. refuses a syntactically valid document whose SessionStart is not an array, touching no bytes and leaving no temp file', async () => {
    const t = await target();
    const original = '{\n  "hooks": { "SessionStart": { "0": "not an array" } },\n  "keep": true\n}\n';
    await writeFile(t.settingsFile, original);
    await expect(installHook(t)).rejects.toThrow(`Cannot edit ${t.settingsFile}: it is not valid JSON. Fix it by hand or move it aside, then re-run.`);
    expect(await readFile(t.settingsFile, 'utf8')).toBe(original);
    expect((await readdir(t.root)).sort()).toEqual(['backups', 'settings.json']);
    expect(await backups(t.backupDir)).toEqual([]);
  });

  it('5. remove deletes every match, keeps the non-matching sibling, other events, and unrelated keys, and backs up once', async () => {
    const t = await target();
    const original = JSON.stringify({ name: 'mine', hooks: { SessionStart: [{ hooks: [{ command: 'terum-skills one' }] }, { hooks: [{ command: 'echo preserve' }] }, { hooks: [{ command: 'x terum-skills y' }] }], Stop: [{ hooks: [{ command: 'echo stop' }] }] } });
    await writeFile(t.settingsFile, original);
    await expect(removeHook(t)).resolves.toBe('removed');
    expect(JSON.parse(await readFile(t.settingsFile, 'utf8'))).toEqual({ name: 'mine', hooks: { SessionStart: [{ hooks: [{ command: 'echo preserve' }] }], Stop: [{ hooks: [{ command: 'echo stop' }] }] } });
    const saved = await backups(t.backupDir);
    expect(saved).toHaveLength(1);
    expect(await readFile(join(t.backupDir, saved[0]!), 'utf8')).toBe(original);
  });

  it('6. removing the last match prunes SessionStart and then hooks, but never the file or its other keys', async () => {
    const t = await target();
    await writeFile(t.settingsFile, JSON.stringify({ project: 'p', hooks: { SessionStart: [HOOK_ENTRY] } }));
    await expect(removeHook(t)).resolves.toBe('removed');
    expect(JSON.parse(await readFile(t.settingsFile, 'utf8'))).toEqual({ project: 'p' });
    expect(await backups(t.backupDir)).toHaveLength(1);
  });

  it('7. a near-match that differs only in case is no match: remove reports absent and rewrites nothing', async () => {
    const t = await target();
    const original = '{\n    "hooks": {\n        "SessionStart": [{"hooks": [{"command": "echo TERUM-SKILLS"}]}]\n    },\n    "x": 1\n}\n';
    await writeFile(t.settingsFile, original);
    const before = (await stat(t.settingsFile)).mtimeMs;
    await expect(removeHook(t)).resolves.toBe('absent');
    expect(await readFile(t.settingsFile, 'utf8')).toBe(original);
    expect((await stat(t.settingsFile)).mtimeMs).toBe(before);
    expect(await backups(t.backupDir)).toEqual([]);
  });

  it('8. hookInstalled: absent → false, unparseable → the Cannot-edit error, a loose spelling → false, substring containment → true; none of them writes', async () => {
    const t = await target();
    const invalid = join(t.root, 'invalid.json'); await writeFile(invalid, '{"hooks":');
    const nonmatching = join(t.root, 'nonmatching.json'); await writeFile(nonmatching, JSON.stringify({ hooks: { SessionStart: [{ hooks: [{ command: 'echo terum skills' }] }] } }));
    const matching = join(t.root, 'matching.json'); await writeFile(matching, JSON.stringify({ hooks: { SessionStart: [{ hooks: [{ command: 'prefix-terum-skills-suffix' }] }] } }));
    await expect(hookInstalled(join(t.root, 'missing.json'))).resolves.toBe(false);
    await expect(hookInstalled(invalid)).rejects.toThrow('is not valid JSON');
    await expect(hookInstalled(nonmatching)).resolves.toBe(false);
    await expect(hookInstalled(matching)).resolves.toBe(true);
    expect(await readFile(invalid, 'utf8')).toBe('{"hooks":');
    expect((await readdir(t.root)).sort()).toEqual(['backups', 'invalid.json', 'matching.json', 'nonmatching.json']);
  });
});
